load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "LibHipCompiler",
    srcs = glob(["*.cpp"]),
    deps = [
        "//include:hip_headers",
        "//include:foundation_headers",
        "//lib/Dialect/IR:HipDialectIR",
        "//lib/Dialect/Transforms:HipDialectTransforms",
        "//lib/Conversion/OnnxToHip:OnnxToHip",
        "//lib/Conversion/HipToLLVM:HipToLLVM",
        "//lib/Conversion/OnnxToHipDNN:OnnxToHipDNN",
        "//lib/Target/LLVM:HipTargetLLVM",
        "//schemas:HipSchemasLib",
        "@llvm-project-overlay//mlir:IR",
        "@llvm-project-overlay//mlir:Pass",
        "@llvm-project-overlay//mlir:Support",
        "@llvm-project-overlay//mlir:Transforms",
        "@llvm-project-overlay//mlir:FuncDialect",
        "@llvm-project-overlay//mlir:ArithDialect",
        "@llvm-project-overlay//mlir:MemRefDialect",
        "@llvm-project-overlay//mlir:LLVMDialect",
        "@llvm-project-overlay//mlir:BufferizationDialect",
        "@llvm-project-overlay//mlir:BufferizationTransforms",
        "@llvm-project-overlay//mlir:SCFDialect",
        "@llvm-project-overlay//mlir:SCFToControlFlow",
        "@llvm-project-overlay//mlir:Parser",
        "@llvm-project-overlay//mlir:LLVMToLLVMIRTranslation",
        "@llvm-project-overlay//mlir:TargetLLVM",
        "@llvm-project-overlay//llvm:Support",
        "@llvm-project-overlay//llvm:Core",
        "@llvm-project-overlay//llvm:IRReader",
        "@llvm-project-overlay//llvm:Passes",
        "@llvm-project-overlay//llvm:Target",
        "@llvm-project-overlay//llvm:X86CodeGen",
        "@llvm-project-overlay//llvm:X86AsmParser",
    ],
    visibility = ["//visibility:public"],
)
