#!/usr/bin/env python3
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
"""Emit a C++ include file with a byte array + length from a binary file.

Usage: embed_binary_c_array.py <input.bin> <symbol_prefix> <output.inc>

Emits an include-guarded fragment suitable for ``#include`` from exactly one
``.cpp`` (``static`` linkage — no separate TU / no LNK2019 from missing .obj).

Inside the fragment:
  alignas(8) static const unsigned char <prefix>[] = { ... };
  static const size_t <prefix>_len = N;
"""

from __future__ import annotations

import sys


def main() -> None:
    if len(sys.argv) != 4:
        print(
            "usage: embed_binary_c_array.py <input.bin> <symbol_prefix> <output.inc>",
            file=sys.stderr,
        )
        sys.exit(2)
    inp, prefix, outp = sys.argv[1:4]
    with open(inp, "rb") as f:
        blob = f.read()
    guard = f"HIPDNN_{prefix.upper()}_INC"
    lines = [
        "// Generated by embed_binary_c_array.py — do not edit.",
        f"#ifndef {guard}",
        f"#define {guard}",
        "#include <cstddef>",
        f"alignas(8) static const unsigned char {prefix}[] = {{",
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i : i + 16]
        lines.append(
            "  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",",
        )
    lines.append("};")
    lines.append(f"static const size_t {prefix}_len = {len(blob)};")
    lines.append(f"#endif // {guard}")
    with open(outp, "w", encoding="utf-8", newline="\n") as o:
        o.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
