Import-Module "C:\msvsn2022\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
Enter-VsDevShell 4f60a005 -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -host_arch=x64"
Write-Host ""
Write-Host "Visual Studio Developer Shell initialized successfully!"
Write-Host ""
Write-Host "You can now run CMake commands:"
Write-Host "  cmake -G `"Visual Studio 17 2022`" -A x64 -DBUILD_SHARED_LIBS=OFF -B C:/Develop/m/build/morphizen-hipdnn -S . -DCMAKE_INSTALL_PREFIX=C:/Develop/m/local"
Write-Host "  cmake --build C:/Develop/m/build/morphizen-hipdnn --config Debug"
Write-Host ""
