load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

bool_flag(
    name = "with-openssl",
    build_setting_default = True,
    visibility = ["//visibility:public"],
)

config_setting(
    name = "openssl_config",
    flag_values = {":with-openssl": "True"},
)

cc_library(
    name = "encryption",
    srcs = glob(["src/*.cpp"]),
    hdrs = glob(["include/morphizen/*.hpp"]),
    defines = select({
        ":openssl_config": [
            "WITH_OPENSSL=1",
        ],
        "//conditions:default": [
            "WITH_OPENSSL=0",
        ],
    }),
    includes = [
        "include",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps =
        select({
            ":openssl_config": [
                "@openssl//:crypto",
                "@openssl//:ssl",
            ],
            "//conditions:default": [],
        }) + [
            "@glog",
        ],
)
