##
# ** Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
# ** Licensed under the MIT License.
##
set(MODEL_COMPATIBILITY_PROTO_FILES
  src/model_compatibility.proto
)
set(MODEL_COMPATIBILITY_PROTO_SRCS "")
set(MODEL_COMPATIBILITY_PROTO_HDRS "")
set(MODEL_COMPATIBILITY_PROTO_DIR "${CMAKE_CURRENT_BINARY_DIR}/model_compatibility_proto")
set(Protobuf_USE_STATIC_LIBS ON)
find_package(Protobuf CONFIG REQUIRED)
if (NOT EXISTS ${CMAKE_CURRENT_BINARY_DIR}/model_compatibility_proto)
  file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/model_compatibility_proto)
endif()
foreach(MODEL_COMPATIBILITY_PROTO_FILE ${MODEL_COMPATIBILITY_PROTO_FILES})
  get_filename_component(MODEL_COMPATIBILITY_PROTO_FILE_NAME ${MODEL_COMPATIBILITY_PROTO_FILE} NAME_WE)
  message(STATUS "generating proto --- ${MODEL_COMPATIBILITY_PROTO_FILE_NAME}.pb.cc ${MODEL_COMPATIBILITY_PROTO_FILE_NAME}.pb.h")
  add_custom_command(
    OUTPUT
      ${CMAKE_CURRENT_BINARY_DIR}/model_compatibility_proto/${MODEL_COMPATIBILITY_PROTO_FILE_NAME}.pb.cc
      ${CMAKE_CURRENT_BINARY_DIR}/model_compatibility_proto/${MODEL_COMPATIBILITY_PROTO_FILE_NAME}.pb.h
    COMMAND protobuf::protoc
    ARGS
    --cpp_out=${CMAKE_CURRENT_BINARY_DIR}/model_compatibility_proto
    -I ${CMAKE_CURRENT_SOURCE_DIR}/src
    ${CMAKE_CURRENT_SOURCE_DIR}/${MODEL_COMPATIBILITY_PROTO_FILE}
    DEPENDS ${MODEL_COMPATIBILITY_PROTO_FILE})
  list(APPEND MODEL_COMPATIBILITY_PROTO_SRCS ${CMAKE_CURRENT_BINARY_DIR}/model_compatibility_proto/${MODEL_COMPATIBILITY_PROTO_FILE_NAME}.pb.cc)
  list(APPEND MODEL_COMPATIBILITY_PROTO_HDRS ${CMAKE_CURRENT_BINARY_DIR}/model_compatibility_proto/${MODEL_COMPATIBILITY_PROTO_FILE_NAME}.pb.h)
endforeach(MODEL_COMPATIBILITY_PROTO_FILE ${MODEL_COMPATIBILITY_PROTO_FILES})
