#!/usr/bin/env python3
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
"""Hex-embeds a compiled LUT `.fb` into a C++ TU, the same bytes CMake's
`file(READ ... HEX)` would produce for `custom_kernels_<arch>` -- for the
hipcc-only kernel-UT build, which has no CMake. Reuses the same
`k<Op>LutData[]` / `_size` symbol names as each op's `tools/empty_lut_data.cpp`
stub, so the real resolver .cpp links against either unmodified.

Usage: python embed_lut.py <in.fb> <symbol> <out.cpp>
"""
import sys


def main() -> int:
    if len(sys.argv) != 4:
        sys.stderr.write("usage: embed_lut.py <in.fb> <symbol> <out.cpp>\n")
        return 1
    fb_path, symbol, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(fb_path, "rb") as f:
        data = f.read()

    lines = [
        "// Generated by example/common/embed_lut.py -- do not edit, do not commit.",
        "#include <cstddef>",
        "",
        f'extern "C" const unsigned char {symbol}[] = {{',
    ]
    for i in range(0, len(data), 20):
        chunk = data[i : i + 20]
        lines.append("  " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f'extern "C" const size_t {symbol}_size = sizeof({symbol});')
    lines.append("")

    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
