/*
 *     The Xilinx Vitis AI Vaip in this distribution are provided under the
 * following free and permissive binary-only license, but are not provided in
 * source code form.  While the following free and permissive license is similar
 * to the BSD open source license, it is NOT the BSD open source license nor
 * other OSI-approved open source license.
 *
 *Copyright (C) 2023 – 2025 Advanced Micro Devices, Inc. All rights reserved.
 *
 *      Redistribution and use in binary form only, without modification, is
 * permitted provided that the following conditions are met:
 *
 *      1. Redistributions must reproduce the above copyright notice, this list
 * of conditions and the following disclaimer in the documentation and/or other
 * materials provided with the distribution.
 *
 *      2. The name of Xilinx, Inc. may not be used to endorse or promote
 * products redistributed with this software without specific prior written
 * permission.
 *
 *      THIS SOFTWARE IS PROVIDED BY XILINX, INC. "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 * EVENT SHALL XILINX, INC. BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *      PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
 */
#include "morphizen/op_def.hpp"
#include "morphizen/vaip.hpp"
#include <glog/logging.h>
#include <vector>
// generated by xir_ops_genereted_names.inc
#include "./xir_ops_genereted_names.inc"
//
using namespace vaip_core;
namespace {

class BuildInOPs : public OpRegister {
public:
  BuildInOPs(void* state, add_op_t add_op) : OpRegister(state, add_op) {}
  int register_ops() override {
    for (auto& name : XIR_OP_NAMES) {
      AddOp("com.xilinx", XilinxCustomOp::create(name));
    }
    //  TODO: check whether this is dead code, when a subgraph fuse into a node,
    //  the op type is hardcoded to "com.xilinx::super_layer", because the node
    //  has a body, so that the shape info might not be needed.
    //
    // AddOp("com.xilinx", XilinxCustomOp::create("super_layer"));
    //
    AddOp("com.xilinx", XilinxCustomOp::create("unknown"));
    AddOp("com.xilinx", XilinxCustomOp::create("conv2d_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("fix2float"));
    AddOp("com.xilinx", XilinxCustomOp::create("float2fix"));
    AddOp("com.xilinx", XilinxCustomOp::create("depthwise_conv2d_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("conv1d_ncd"));
    AddOp("com.xilinx", XilinxCustomOp::create("depthwise_conv1d_ncd"));
    AddOp("com.xilinx", XilinxCustomOp::create("depthwise_conv1d"));
    AddOp("com.xilinx", XilinxCustomOp::create("transposed_conv2d_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("maxpool2d_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("avgpool2d_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("resize_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("ConvTranspose_nhwc"));
    AddOp("com.xilinx", XilinxCustomOp::create("GlobalAveragePool_nhwc"));
    AddOp("com.xilinx", XilinxCustomOp::create("depthwise_conv2d_ihwo"));
    AddOp("com.xilinx", XilinxCustomOp::create("pixel_shuffle_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("gstiling_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("quantize_linear"));
    AddOp("com.xilinx", XilinxCustomOp::create("dequantize_linear"));
    AddOp("com.xilinx", XilinxCustomOp::create("layernorm"));
    AddOp("com.xilinx", XilinxCustomOp::create("abs"));
    AddOp("com.xilinx", XilinxCustomOp::create("clamp"));
    AddOp("com.xilinx", XilinxCustomOp::create("instancenorm_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("instancenorm_ncd"));
    AddOp("com.xilinx", XilinxCustomOp::create("groupnorm_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("groupnorm_ncd"));
    AddOp("com.xilinx", XilinxCustomOp::create("space_to_depth"));
    AddOp("com.xilinx", XilinxCustomOp::create("space_to_depth_nchw"));
    AddOp("com.xilinx", XilinxCustomOp::create("sqrt"));
    AddOp("com.xilinx", XilinxCustomOp::create("pow"));
    AddOp("com.xilinx", XilinxCustomOp::create("gather"));
    AddOp("com.xilinx", XilinxCustomOp::create("expand"));
    AddOp("com.xilinx", XilinxCustomOp::create("reduction_min"));
    AddOp("com.xilinx", XilinxCustomOp::create("broadcast_tile"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMHAGRPB"));
    AddOp("com.xilinx", XilinxCustomOp::create("DQAdd"));
    AddOp("com.xilinx", XilinxCustomOp::create("QActConstAdd"));
    AddOp("com.xilinx", XilinxCustomOp::create("QExpand"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMatMul"));
    AddOp("com.xilinx", XilinxCustomOp::create("QBatchMatMul"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMatMulAdd"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMatMulAddGelu"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMatMulAddSilu"));
    AddOp("com.xilinx", XilinxCustomOp::create("QGemmvGelu"));
    AddOp("com.xilinx", XilinxCustomOp::create("mzdk5MHA"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMatMulDynamic"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMatMulDynamicSoftmax"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMulSoftmax"));
    AddOp("com.xilinx", XilinxCustomOp::create("QLayerNorm"));
    AddOp("com.xilinx", XilinxCustomOp::create("QEltWiseAdd"));
    AddOp("com.xilinx", XilinxCustomOp::create("QEltWiseDiv"));
    AddOp("com.xilinx", XilinxCustomOp::create("QGlobalAvgPool"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMHA"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMHACHANNEL"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMHAWINDOW"));
    AddOp("com.xilinx", XilinxCustomOp::create("IConv"));
    AddOp("com.xilinx", XilinxCustomOp::create("QReshapeTranspose"));
    AddOp("com.xilinx", XilinxCustomOp::create("QConv"));
    AddOp("com.xilinx", XilinxCustomOp::create("QReduceSum"));
    AddOp("com.xilinx", XilinxCustomOp::create("QConcateOPs"));
    AddOp("com.xilinx", XilinxCustomOp::create("QLstm"));
    AddOp("com.xilinx", XilinxCustomOp::create("QL2norm"));
    AddOp("com.xilinx", XilinxCustomOp::create("L2_Norm"));
    AddOp("com.xilinx", XilinxCustomOp::create("QConv2MatMulSilu"));
    AddOp("com.xilinx", XilinxCustomOp::create("QRopeConst"));
    AddOp("com.xilinx", XilinxCustomOp::create("QRopeInput"));
    AddOp("com.xilinx", XilinxCustomOp::create("QGroupNorm"));
    AddOp("com.xilinx", XilinxCustomOp::create("QConv2MatMul"));
    AddOp("com.xilinx", XilinxCustomOp::create("QELWEMUL_qdq"));
    AddOp("com.xilinx", XilinxCustomOp::create("QELWEMUL_mxgan"));
    AddOp("com.xilinx", XilinxCustomOp::create("QSlice"));
    AddOp("com.xilinx", XilinxCustomOp::create("DPS"));
    AddOp("com.xilinx", XilinxCustomOp::create("QConcat"));
    AddOp("com.xilinx", XilinxCustomOp::create("QSilu"));
    AddOp("com.xilinx", XilinxCustomOp::create("SILU"));
    AddOp("com.xilinx", XilinxCustomOp::create("AttentionMaskPrePro"));
    AddOp("com.xilinx", XilinxCustomOp::create("AttentionMaskPrePro_win25"));
    AddOp("com.xilinx", XilinxCustomOp::create("QResize"));
    AddOp("com.xilinx", XilinxCustomOp::create("QuantOP"));
    AddOp("com.xilinx", XilinxCustomOp::create("DeQuantOP"));
    AddOp("com.xilinx", XilinxCustomOp::create("QGelu"));
    AddOp("com.xilinx", XilinxCustomOp::create("QBroadcastAdd"));
    AddOp("com.xilinx", XilinxCustomOp::create("QBroadcastBiasAdd"));
    AddOp("com.xilinx", XilinxCustomOp::create("Mladfelwmul"));
    AddOp("com.xilinx", XilinxCustomOp::create("ELWMUL"));
    AddOp("com.xilinx", XilinxCustomOp::create("MLADFMATMULA16A16"));
    AddOp("com.xilinx", XilinxCustomOp::create("MladfMatMul"));
    AddOp("com.xilinx", XilinxCustomOp::create("VAIMLQMatmul"));
    AddOp("com.xilinx", XilinxCustomOp::create("FlatMLP"));
    AddOp("com.xilinx", XilinxCustomOp::create("Qtanh_lpnorm"));
    AddOp("com.xilinx", XilinxCustomOp::create("MLADFRMSNORM"));
    AddOp("com.xilinx", XilinxCustomOp::create("Mladfsoftmax"));
    AddOp("com.xilinx", XilinxCustomOp::create("QSigmoid"));
    AddOp("com.xilinx", XilinxCustomOp::create("MLADFADD"));
    AddOp("com.xilinx", XilinxCustomOp::create("Qbias_add"));
    AddOp("com.xilinx", XilinxCustomOp::create("round"));
    AddOp("com.xilinx", XilinxCustomOp::create("equal"));
    AddOp("com.xilinx", XilinxCustomOp::create("reciprocal"));
    AddOp("com.xilinx", XilinxCustomOp::create("QDeMHA"));
    AddOp("com.xilinx", XilinxCustomOp::create("QGatherDivAdd"));
    AddOp("com.xilinx", XilinxCustomOp::create("QIntEltwiseAdd"));
    AddOp("com.xilinx", XilinxCustomOp::create("QIntEltwiseMul"));
    AddOp("com.xilinx", XilinxCustomOp::create("QLinear_CPU"));
    AddOp("com.xilinx", XilinxCustomOp::create("DQLinear_CPU"));
    AddOp("com.xilinx", XilinxCustomOp::create("DQSoftmax_CPU"));
    AddOp("com.xilinx", XilinxCustomOp::create("Transpose_CPU"));
    AddOp("com.xilinx", XilinxCustomOp::create("einsum"));
    AddOp("com.xilinx", XilinxCustomOp::create("VAIMLQMatmul"));
    AddOp("com.xilinx", XilinxCustomOp::create("VAIMLQSilu"));
    AddOp("com.xilinx", XilinxCustomOp::create("VAIMLQRMSNorm"));
    AddOp("com.xilinx", XilinxCustomOp::create("VAIMLQElwise"));
    AddOp("com.xilinx", XilinxCustomOp::create("QMatmulDynamicTranspose"));
    AddOp("com.xilinx", XilinxCustomOp::create("QGemmTanh"));
    AddOp("com.xilinx", XilinxCustomOp::create("NoOp"));
    return 0;
  }
};
static int register_ops(void* state, add_op_t add_op) {
  return BuildInOPs(state, add_op).register_ops();
}
static ::vaip_core::StaticPluginRegister __register("morphizen-core-static",
                                                    "morphizen_register_ops",
                                                    (void*)&register_ops);
} // namespace
void* BuildInOPs__hook = &__register;
