#!/usr/bin/env python3

#
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
#

"""
Sweep a matrix of shapes through the built gemm_fp16u2 test binary WITH
zero_points, and summarize the "u2 packed-zp real-model path vs u4 with zp"
performance into zp_perf_compare.md (this folder).

For each shape this:
  1. generates with-zeros data via gen_matmul_nbits_u2_data.py,
  2. runs build/test_direct.exe on that shape,
  3. parses the steady-state packed-zp benchmark line
        u2(pkd-zp) vs u4(zp) speed: R x (...)  [u2 G GFLOPS / B GB/s  vs  u4 ...]
     plus the unpack-check and Overall pass/fail.

The u2(pkd-zp) number is the real runtime path: the ONNX 2-bit packed
zero_points are unpacked to one-byte-per-group once (excluded from timing, as
the wrapper caches per pointer), then the GEMM is timed with pre_unpacked_zp_u8.

Prerequisites: build the project first, e.g.
  make direct HIP_SDK=... OFFLOAD=--offload-arch=gfxNNNN
Run with a python that has numpy (used only by the data gen), e.g.
  C:\\tools\\Anaconda3\\python.exe bench_zp_perf.py
"""

import os
import re
import sys
import shutil
import subprocess

BITS = 2
HERE = os.path.dirname(os.path.abspath(__file__))
ROCM_BIN = r"C:\Users\a1_iputest\Documents\Workspace\ROCm\7.1\bin"
GPU = "AMD Radeon 8060S (gfx1151)"
OUT_MD = os.path.join(HERE, "zp_perf_compare.md")

# (M, K, N, group_size). K must be a multiple of 32.
SHAPES = [
    # decode (M=1) — memory-bound, where low-bit weight traffic pays off
    (1,   2880, 2880, 128),
    (1,   2880, 5120, 128),
    (1,   4096, 2880, 128),
    (1,   2880, 4096, 128),
    (1,   5120, 5120, 128),
    (1,   2880, 2880, 64),
    # small prefill (M=128) — WMMA fast path
    (128, 2880, 2880, 128),
    (128, 2880, 5120, 128),
    (128, 4096, 2880, 128),
    (128, 2880, 4096, 128),
    (128, 5120, 5120, 128),
    (128, 2880, 2880, 64),
    # larger prefill (M=512)
    (512, 2880, 2880, 128),
    (512, 2880, 5120, 128),
    (512, 4096, 2880, 128),
]

SPEED_RE = re.compile(
    r"u\d\(pkd-zp\) vs u4\(zp\) speed: ([\d.]+)x \(([^)]+)\)\s+"
    r"\[u\d ([\d.]+) GFLOPS / ([\d.]+) GB/s\s+vs\s+"
    r"u4 ([\d.]+) GFLOPS / ([\d.]+) GB/s\]")
UNPACK_RE = re.compile(r"Unpack check: (\d+)/(\d+).*?(PASS|FAIL)")
OVERALL_RE = re.compile(r"Overall: (ALL PASSED|SOME FAILED)")


def run_shape(M, K, N, gs):
    gen = os.path.join(HERE, f"gen_matmul_nbits_u{BITS}_data.py")
    exe = os.path.join(HERE, "build", "test_direct.exe")
    if not os.path.isfile(exe):
        raise RuntimeError(f"missing {exe} — build it first (make direct ...)")
    data_dir = os.path.join(HERE, f"_zpbench_{M}x{K}x{N}_gs{gs}")

    size = f"{M}x{K}x{N}"
    subprocess.run([sys.executable, gen, size, "--group-size", str(gs),
                    "--dir", data_dir],
                   check=True, cwd=HERE,
                   stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)

    env = dict(os.environ)
    env["PATH"] = ROCM_BIN + os.pathsep + env.get("PATH", "")
    out = subprocess.run([exe, size, str(gs), data_dir],
                         cwd=HERE, env=env, capture_output=True, text=True)
    shutil.rmtree(data_dir, ignore_errors=True)

    text = out.stdout + "\n" + out.stderr
    sp = SPEED_RE.search(text)
    up = UNPACK_RE.search(text)
    ov = OVERALL_RE.search(text)
    if not sp:
        return None
    return {
        "speedup": float(sp.group(1)),
        "winner": sp.group(2),
        "ux_gflops": float(sp.group(3)),
        "ux_bw": float(sp.group(4)),
        "u4_gflops": float(sp.group(5)),
        "u4_bw": float(sp.group(6)),
        "unpack": (up.group(3) if up else "N/A"),
        "overall": (ov.group(1) if ov else "UNKNOWN"),
    }


def main():
    rows = []
    for (M, K, N, gs) in SHAPES:
        print(f"[u{BITS}] {M}x{K}x{N} gs{gs} ...", flush=True)
        rows.append(((M, K, N, gs), run_shape(M, K, N, gs)))

    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write(f"# MatMulNBits u{BITS} vs u4 — with zero_points performance\n\n")
        f.write(
            f"Steady-state performance of the **packed zero_points real-model "
            f"path** for {BITS}-bit (u{BITS}) weights, compared head-to-head "
            f"against 4-bit (u4) **with zero_points** on identical "
            f"(M, K, N, group_size) shapes. Generated by `bench_zp_perf.py`.\n\n")
        f.write(
            f"The `u{BITS}(pkd-zp)` number mirrors the runtime: the ONNX-packed "
            f"zero_points are unpacked to one-byte-per-group **once** (excluded "
            f"from timing, as the wrapper caches per pointer), then the GEMM is "
            f"timed with `zero_points`=packed blob + `pre_unpacked_zp_u8`="
            f"unpacked buffer. GFLOP/s uses the same FLOP count for all kernels "
            f"(fair throughput metric); GB/s reflects actual bytes moved (u4 "
            f"moves more weight bytes). `speed` is the u4/u{BITS} median-time "
            f"ratio (>1 means u{BITS} is faster).\n\n")
        f.write(f"- GPU: {GPU}\n")
        f.write("- All shapes run WITH zero_points (asymmetric quantization).\n")
        f.write("- `unpack` = packed -> one-byte-per-group byte-exact check; "
                "`verify` = full GEMM vs FP32 NumPy reference.\n\n")
        f.write(
            f"| M | K | N | GS | u{BITS} GFLOP/s | u{BITS} GB/s | u4 GFLOP/s "
            f"| u4 GB/s | u{BITS}/u4 speed | unpack | verify |\n")
        f.write("|--:|--:|--:|--:|--:|--:|--:|--:|:--:|:--:|:--:|\n")
        for (M, K, N, gs), r in rows:
            if r is None:
                f.write(f"| {M} | {K} | {N} | {gs} | — | — | — | — | FAILED | — | — |\n")
                continue
            speed = f"{r['speedup']:.2f}x ({r['winner']})"
            verify = "PASS" if r["overall"] == "ALL PASSED" else "FAIL"
            f.write(
                f"| {M} | {K} | {N} | {gs} | {r['ux_gflops']:.0f} | {r['ux_bw']:.1f} "
                f"| {r['u4_gflops']:.0f} | {r['u4_bw']:.1f} | {speed} "
                f"| {r['unpack']} | {verify} |\n")
        f.write("\n#### Notes\n\n")
        f.write(
            "- **Decode (M=1)** is memory-bound: reducing weight bytes directly "
            f"reduces latency, so u{BITS} tends to beat u4 here.\n"
            "- **Prefill (M=128/512)** hits the WMMA path and is compute-bound: "
            "all bit-widths saturate the tensor cores, so throughput is ~parity "
            "(the low-bit weight-size win shows up as GB/s headroom, not "
            "GFLOP/s).\n")

    print(f"\nWrote {OUT_MD}")


if __name__ == "__main__":
    main()
