// Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
// Licensed under the MIT License.
//
//===----------------------------------------------------------------------===//
// Converts onnx.Cast to hipsr.cast. Unlike a round-trip test, this exercises
// CastOp::populateShapeRegion() (the single source of truth): the shape region
// is generated by the implementation, not written by hand.
//===----------------------------------------------------------------------===//

// RUN: hip-mlir-opt %s -allow-unregistered-dialect -convert-onnx-to-hipsr | FileCheck %s

// CHECK-LABEL: func.func @cast
func.func @cast(%input: tensor<?x8xf32>) -> tensor<?x8xf16> {
  // CHECK: %[[D0:.+]] = tensor.dim %[[IN:.+]], %{{.+}} : tensor<?x8xf32>
  // CHECK: %[[INIT:.+]] = tensor.empty(%[[D0]]) : tensor<?x8xf16>
  // CHECK: hipsr.cast ins(%[[IN]] : tensor<?x8xf32>) outs(%[[INIT]] : tensor<?x8xf16>) -> tensor<?x8xf16> shape_region {
  // CHECK:   %[[S:.+]] = shape.shape_of %[[IN]]
  // CHECK:   shape.get_extent %[[S]]
  // CHECK:   hipsr.shape_yield
  // CHECK: }
  %0 = "onnx.Cast"(%input) : (tensor<?x8xf32>) -> tensor<?x8xf16>
  return %0 : tensor<?x8xf16>
}
