load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "HipDialectTransforms",
    srcs = [
        "AddHipContextArg.cpp",
        "BufferUtils.cpp",
        "GenerateInterface.cpp",
        "LowerAllocs.cpp",
        "OptimizeMemRefs.cpp",
        "Pipelines.cpp",
        "PoolAllocs.cpp",
        "ResolveExternConstants.cpp",
    ],
    deps = [
        "//include:hip_headers",
        "//include/hip/Dialect/IR:HipDialectIncGen",
        "//include/hip/Dialect/IR:HipTypesIncGen",
        "//include/hip/Dialect/IR:HipOpsIncGen",
        "//include/hip/Dialect/Transforms:HipPassesIncGen",
        "//lib/Dialect/IR:HipDialectIR",
        "//lib/Conversion/HipToLLVM:HipToLLVM",
        "//lib/Conversion/OnnxToHip:OnnxToHip",
        "//lib/Conversion/OnnxToHipDNN:OnnxToHipDNN",
        "//schemas:HipSchemasLib",
        "@llvm-project-overlay//mlir:Pass",
        "@llvm-project-overlay//mlir:Transforms",
        "@llvm-project-overlay//mlir:FuncDialect",
        "@llvm-project-overlay//mlir:MemRefDialect",
        "@llvm-project-overlay//mlir:ArithDialect",
        "@llvm-project-overlay//mlir:LLVMDialect",
        "@llvm-project-overlay//mlir:BufferizationDialect",
        "@llvm-project-overlay//mlir:BufferizationTransforms",
        "@llvm-project-overlay//mlir:BufferizationPipelines",
        "@llvm-project-overlay//mlir:BufferizationToMemRef",
        "@llvm-project-overlay//mlir:ArithToLLVM",
        "@llvm-project-overlay//mlir:MemRefToLLVM",
        "@llvm-project-overlay//mlir:FuncToLLVM",
        "@llvm-project-overlay//mlir:ReconcileUnrealizedCasts",
        "@flatbuffers//:runtime_cc",
    ],
    visibility = ["//visibility:public"],
)
