/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 * Licensed under the MIT License.
 */
#pragma once

#include <cstddef>
#include <cstdint>

namespace mlir_compilation {

// ============================================================================
// Data structures — C-compatible, stable ABI
// ============================================================================

// Describes a single tensor passed across the DLL boundary.
// All memory is caller-owned CPU memory; the DLL copies H2D/D2H internally.
struct tensor_t {
  void *data; // Pointer to contiguous tensor data (CPU memory, caller-owned)
  int64_t *shape; // Pointer to shape array of length `rank` (caller-owned)
  size_t rank;    // Number of dimensions (must match the compiled model's rank)
  size_t element_size; // Bytes per element (e.g. 4=float32, 2=float16, 8=int64)
};

// A contiguous array of tensor_t descriptors (inputs or outputs).
struct span_t {
  tensor_t *data; // Pointer to array of tensor_t
  size_t count; // Number of tensors (must match the compiled model's I/O count)
};

// ============================================================================
// DLL function pointer typedefs — stable C ABI exported by the compiled model.
//
// Generated by GenerateInterfacePass in morphizen-mlir-compiler.
// Full interface design:
// morphizen-mlir-compiler/doc/design/mlir/INTERFACE-DESIGN.md
//
// Lifecycle contract:
//   void* state = nullptr;
//   init_fn(&state);           // once: allocates GPU handles, uploads weights
//   compute_fn(state, in, out); // N times: H2D → compute → D2H → stream sync
//   cleanup_fn(state);         // once: releases all GPU resources
//
// All functions return 0 on success, non-zero on failure.
// ============================================================================

// One-time initialisation: creates GPU stream, MIOpen/hipBLAS handles, and
// uploads compiled model weights to device memory.
//
// Parameters:
//   out_state  [out] Receives the allocated opaque context pointer on success.
//                    Pass &state where state is a void* initialised to nullptr.
//
// Return values:
//   0  Success
//   1  Context allocation failed (malloc)
//   2  GPU handle creation failed (stream, MIOpen, or hipBLAS)
//   3  Constant upload to GPU failed
typedef int (*init_fn)(void **out_state);

// Executes one inference pass: copies inputs to GPU, runs the compiled graph,
// copies outputs back to CPU, then synchronises the stream.
//
// Parameters:
//   state    [in]     Opaque context pointer returned by init_fn.
//   inputs   [in]     span_t of host-memory input tensors.
//                     tensor_t.count and each tensor_t.rank must match the
//                     compiled model; tensor_t.shape supplies runtime
//                     dimensions.
//   outputs  [in/out] span_t of host-memory output tensors (caller-allocated).
//                     The DLL writes results into tensor_t.data on success.
//
// Return values:
//   0  Success
//   5  Invalid input (wrong tensor count, rank mismatch, or null pointer)
//   8  Computation failed (GPU kernel error)
//   9  Memory transfer failed (H2D or D2H copy)
typedef int (*compute_fn)(void *state, span_t *inputs, span_t *outputs);

// Releases all GPU resources acquired by init_fn.
// Best-effort: continues freeing remaining resources even if one step fails.
// state is invalid after this call regardless of return value.
//
// Parameters:
//   state  [in] Opaque context pointer returned by init_fn.
//
// Return values:
//   0   Success
//   10  Stream destruction failed
//   11  MIOpen handle destruction failed
//   12  hipBLAS handle destruction failed
//   13  GPU constant memory release failed (potential GPU memory leak)
//   14  Stream synchronisation failed
typedef int (*cleanup_fn)(void *state);

} // namespace mlir_compilation
