/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 * Licensed under the MIT License.
 */
#pragma once

#include <cstddef>
#include <cstdint>

namespace mlir_compilation {

// Interface types for DLL communication.
// These match the C interface generated by GenerateInterfacePass in the
// morphizen-mlir-compiler. See custom_op_mlir.hpp for the full contract.
struct tensor_t {
  void *data;     // Pointer to tensor data
  int64_t *shape; // Pointer to shape array
  size_t rank;    // Number of dimensions
};

struct span_t {
  tensor_t *data; // Pointer to tensor array
  size_t count;   // Number of tensors
};

// DLL function pointers — stable C ABI exported by the compiled model DLL.
// Lifecycle: call init once, compute N times, cleanup once.
// All return 0 on success, non-zero on failure.

// One-time initialisation: allocates GPU handles (stream, MIOpen, hipBLAS)
// and uploads model weights to device memory.
// out_state receives the allocated opaque context pointer on success.
typedef int (*init_fn)(void **out_state);

// Runs inference: copies inputs H2D, calls the compiled graph, copies outputs
// D2H, then synchronises the GPU stream.
// state is the opaque context pointer returned by init_fn.
// inputs/outputs are host-memory tensor arrays; count must match the compiled model.
typedef int (*compute_fn)(void *state, span_t *inputs, span_t *outputs);

// Releases all GPU resources acquired by init_fn (handles, device memory).
// state is invalid after this call. Best-effort cleanup runs even on error.
typedef int (*cleanup_fn)(void *state);

} // namespace mlir_compilation
