/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 * Licensed under the MIT License.
 */
#pragma once

#include <cstddef>
#include <cstdint>

namespace mlir_compilation {

// Interface types for DLL communication
// These match the interface generated by GenerateInterfacePass
struct tensor_t {
  void *data;     // Pointer to tensor data
  int64_t *shape; // Pointer to shape array
  size_t rank;    // Number of dimensions
};

struct span_t {
  tensor_t *data; // Pointer to tensor array
  size_t count;   // Number of tensors
};

// DLL function pointers
typedef int (*init_fn)(void **);
typedef int (*compute_fn)(void *, span_t *, span_t *);
typedef int (*cleanup_fn)(void *);

} // namespace mlir_compilation
