/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 * Licensed under the MIT License.
 */
#include "InferenceState.h"

// CRITICAL: morphizen.hpp must be included before other morphizen headers
#include "../../common/temp_path.hpp"
#include "hip/timing.h"
#include "morphizen/env_config.hpp"
#include "morphizen/morphizen.hpp"
#include "morphizen/plugin.hpp"
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <glog/logging.h>
#include <string>
#include <utility>

#include <morphizen-foundation/file_io.hpp>

// Environment parameters (global scope, before namespace)
DEF_ENV_PARAM(MORPHIZEN_DEBUG_MLIR_BACKEND, "0")

#define MY_LOG(n) LOG_IF(INFO, ENV_PARAM(MORPHIZEN_DEBUG_MLIR_BACKEND) >= n)

namespace {
std::string artifactExtension() {
#ifdef _WIN32
  return ".dll";
#else
  return ".so";
#endif
}

// Extract constants_filename from the JSON returned by
// inference_get_metadata_json.  The JSON is generated by GenerateInterface
// and always contains a top-level "constants_filename" key when constants
// were externalized.  A lightweight search avoids pulling in a JSON parser.
std::string extractConstantsFilename(const char *json) {
  if (!json)
    return {};
  const char *key = "\"constants_filename\"";
  const char *pos = std::strstr(json, key);
  if (!pos)
    return {};
  pos += std::strlen(key);
  while (*pos && (*pos == ' ' || *pos == ':' || *pos == '\t'))
    ++pos;
  if (*pos != '"')
    return {};
  ++pos;
  const char *end = std::strchr(pos, '"');
  if (!end)
    return {};
  return {pos, static_cast<size_t>(end - pos)};
}
} // anonymous namespace

namespace mlir_compilation::customop {

InferenceState::InferenceState(PrivateTag, void *state,
                               std::unique_ptr<morphizen::Plugin> plugin,
                               const std::string &temp_dll_path)
    : state_(state), plugin_(std::move(plugin)), temp_dll_path_(temp_dll_path) {
}

std::unique_ptr<InferenceState>
InferenceState::create(const std::vector<uint8_t> &dll_bytes,
                       morphizen::FileSystem *fs) {
  MY_LOG(1) << "Loading inference plugin from memory...";

  auto t0 = timing_now();
  auto t_prev = t0;

  // Write DLL to temp file (morphizen::Plugin loads from file path)
  std::string dll_path =
      mlir_compiler_utils::generateTempPath(artifactExtension());
  MY_LOG(2) << "Temporary DLL path: " << dll_path;

  // Write DLL to temp file
  {
    std::ofstream dll_out(dll_path, std::ios::binary);
    if (!dll_out) {
      LOG(FATAL) << "Failed to create temporary DLL file: " << dll_path;
    }
    dll_out.write(reinterpret_cast<const char *>(dll_bytes.data()),
                  dll_bytes.size());
    dll_out.close();
  }

  TIMING_LOG("[Session] Write DLL to temp file: %.3fs (%zu bytes)\n",
             record_elapsed(t_prev), dll_bytes.size());

  // Load plugin using morphizen infrastructure (factory pattern)
  // Pass path without extension — Plugin::guess_name adds platform-correct
  // suffix
  std::string base_path =
      std::filesystem::path(dll_path).replace_extension("").string();
  auto plugin = morphizen::Plugin::create(base_path.c_str());

  // Check if plugin DLL loaded successfully
  if (!plugin) {
    LOG(FATAL)
        << "Failed to load DLL: " << dll_path
        << " - check that the file exists and all dependencies are available";
  }

  TIMING_LOG("[Session] Plugin::create (LoadLibrary): %.3fs\n",
             record_elapsed(t_prev));

  auto init_fn = plugin->get_method<int, void **, void *>("inference_init");
  if (!init_fn) {
    LOG(FATAL) << "inference_init function not found in plugin: " << dll_path
               << " - DLL loaded successfully but symbol is missing";
  }

  TIMING_LOG("[Session] get_method (symbol lookup): %.3fs\n",
             record_elapsed(t_prev));

  // When the underlying FileSystem is file-backed (EP-context loaded from
  // disk), TarEntryInputStream::mmap() returns nullptr and the runtime falls
  // back to chunked fread().  Pre-reading the constants into a contiguous
  // host buffer and serving it through an OverlayFileSystem gives the
  // runtime a guaranteed-mmap reader, avoiding that overhead.
  //
  // For the first-run case the tar is already memory-backed and mmap()
  // works, so the overlay is skipped -- the runtime gets the fast path
  // directly from the tar FileSystem without any extra work.
  std::unique_ptr<morphizen::OverlayFileSystem> overlay_fs;
  std::shared_ptr<std::vector<uint8_t>> constants_buf;
  morphizen::FileSystem *init_fs = fs;

  auto meta_fn =
      plugin->get_method<const char *>("inference_get_metadata_json");
  if (meta_fn) {
    std::string cfile = extractConstantsFilename(meta_fn());
    if (!cfile.empty()) {
      auto reader = fs->create_reader_template(cfile.c_str());
      if (reader && reader->size() > 0 && !reader->mmap()) {
        // File-backed (EP-context loaded from disk).  Bulk-read into a
        // host buffer so the runtime gets mmap() == non-null.
        size_t total = reader->size();
        constants_buf = std::make_shared<std::vector<uint8_t>>(total);
        reader->rewind();
        size_t got = reader->fread(constants_buf->data(), total);
        if (got == total) {
          overlay_fs = std::make_unique<morphizen::OverlayFileSystem>(fs);
          overlay_fs->add_overlay(cfile, constants_buf);
          init_fs = overlay_fs.get();
          MY_LOG(1) << "Constants overlay: pre-read " << total << " bytes";
        } else {
          MY_LOG(1) << "Constants pre-read short (" << got << "/" << total
                    << "), falling back to original fs";
          constants_buf.reset();
        }
        TIMING_LOG("[Session] Constants pre-read: %.3fs\n",
                   record_elapsed(t_prev));
      }
    }
  }

  void *state = nullptr;
  int ret = init_fn(&state, static_cast<void *>(init_fs));
  if (ret != 0) {
    LOG(FATAL) << "inference_init() failed with code: " << ret;
  }

  TIMING_LOG("[Session] inference_init: %.3fs\n", record_elapsed(t_prev));
  TIMING_LOG("[Session] InferenceState::create total: %.3fs\n",
             elapsed_since(t0));

  MY_LOG(1) << "Inference state initialized";

  return std::make_unique<InferenceState>(PrivateTag{}, state,
                                          std::move(plugin), dll_path);
}

InferenceState::~InferenceState() {
  MY_LOG(1) << "InferenceState destructor: cleaning up state";
  if (state_ && plugin_) {
    auto cleanup_fn = plugin_->get_method<int, void *>("inference_cleanup");
    if (cleanup_fn) {
      int ret = cleanup_fn(state_);
      if (ret != 0) {
        LOG(WARNING) << "inference_cleanup() failed with code: " << ret;
      }
    }
    state_ = nullptr;
  }
  MY_LOG(1) << "InferenceState destructor: plugin will be destroyed next";
  // plugin_ destructor runs automatically after this

  // Delete temporary DLL file after plugin is destroyed
  if (!temp_dll_path_.empty()) {
    std::remove(temp_dll_path_.c_str());
    MY_LOG(2) << "Deleted temporary DLL: " << temp_dll_path_;
  }
}

int InferenceState::compute(span_t *inputs, span_t *outputs) const {
  auto compute_fn =
      plugin_->get_method<int, void *, span_t *, span_t *>("inference_compute");
  if (!compute_fn) {
    LOG(ERROR) << "inference_compute function not found in plugin";
    return -1;
  }
  return compute_fn(state_, inputs, outputs);
}

} // namespace mlir_compilation::customop
