/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 * Licensed under the MIT License.
 *
 * Minimal compile-time shim for AMDMLSS headers when building hip-ep runtime
 * bitcode. The real amdmlss_export.h is generated by AMDMLSS CMake; hip-ep
 * dlopens amdmlss.dll at runtime and does not link against MLSS_API symbols.
 */
#pragma once

#ifndef MLSS_API
#define MLSS_API
#endif

#ifndef MLSS_NO_EXPORT
#define MLSS_NO_EXPORT
#endif
