load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "HipToLLVM",
    srcs = glob(["*.cpp"]) + glob(["*.h"]),
    deps = [
        "//include:hip_headers",
        "//include/hip/Dialect/IR:HipDialectIncGen",
        "//include/hip/Dialect/IR:HipTypesIncGen",
        "//include/hip/Dialect/IR:HipOpsIncGen",
        "//include/hip/Dialect/Transforms:HipPassesIncGen",
        "//lib/Dialect/IR:HipDialectIR",
        "@llvm-project-overlay//mlir:Pass",
        "@llvm-project-overlay//mlir:LLVMDialect",
        "@llvm-project-overlay//mlir:LLVMCommonConversion",
        "@llvm-project-overlay//mlir:ArithToLLVM",
        "@llvm-project-overlay//mlir:ControlFlowToLLVM",
        "@llvm-project-overlay//mlir:FuncToLLVM",
        "@llvm-project-overlay//mlir:MemRefToLLVM",
        "@llvm-project-overlay//mlir:ArithDialect",
        "@llvm-project-overlay//mlir:ControlFlowDialect",
        "@llvm-project-overlay//mlir:FuncDialect",
        "@llvm-project-overlay//mlir:MemRefDialect",
        "@llvm-project-overlay//mlir:Transforms",
    ],
    visibility = ["//visibility:public"],
)
