# -*- Python -*-
#
# Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
#

# LIT two-file config pattern (from lit's point of view):
#
#   lit.site.cfg.py  — generated by CMake into the BUILD directory; loaded
#                      automatically by lit FIRST because lit searches upward
#                      from the build tree. Its job: inject build-time paths
#                      (tool dirs, build mode) that static source cannot know.
#
#   lit.cfg.py (this file) — static source in the SOURCE directory; loaded
#                      SECOND via lit_config.load_config() at the end of
#                      lit.site.cfg.py. Its job: define the test suite
#                      (name, format, suffixes, substitutions).
#
# Attributes guaranteed to exist when this file runs (set by lit.site.cfg.py):
#   config.llvm_tools_dir  — path to FileCheck, not, etc.
#   config.udna_build_dir  — CMAKE_BINARY_DIR
#   config.udna_build_mode — "Debug" or "Release" (resolved at runtime for VS)

import os
import lit.formats
import lit.llvm

# ruff: noqa: F821  (config/lit_config injected by lit framework)

config.name = "MorphizenMLIR"
config.test_format = lit.formats.ShTest(execute_external=False)
config.suffixes = [".mlir"]
config.test_source_root = os.path.dirname(__file__)
config.test_exec_root = config.test_source_root

# Initialize LLVMConfig using llvm_tools_dir from lit.site.cfg.py.
# This sets up PATH and enables add_tool_substitutions / with_environment.
llvm_config = lit.llvm.config.LLVMConfig(lit_config, config)

# Locate udna tools. Search order:
#   1. <build>/tools/udna-opt/<mode>/  (VS multi-config layout)
#   2. <build>/tools/udna-opt/         (Ninja single-config layout)
#   3. <build>/bin/<mode>
#   4. <build>/bin
udna_tool_search = [
    os.path.join(config.udna_build_dir, "tools", "udna-opt", config.udna_build_mode),
    os.path.join(config.udna_build_dir, "tools", "udna-opt"),
    os.path.join(config.udna_build_dir, "bin", config.udna_build_mode),
    os.path.join(config.udna_build_dir, "bin"),
]
udna_tools_dirs = [d for d in udna_tool_search if os.path.isdir(d)]

# udna-compile may live in a separate directory from udna-opt
udna_compile_dir = os.path.join(config.udna_build_dir, "tools", "udna-compile")
if os.path.isdir(udna_compile_dir) and udna_compile_dir not in udna_tools_dirs:
    udna_tools_dirs.append(udna_compile_dir)

if not udna_tools_dirs:
    udna_tools_dirs = [os.path.join(config.udna_build_dir, "bin")]

llvm_config.with_environment("PATH", udna_tools_dirs, append_path=True)

tools = [
    "udna-opt",
    "udna-compile",
    "FileCheck",
    "not",
]
llvm_config.add_tool_substitutions(tools, udna_tools_dirs + [config.llvm_tools_dir])
