# -*- Python -*-
#
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
#

# LIT two-file config pattern (from lit's point of view):
#
#   lit.site.cfg.py  — generated by CMake into the BUILD directory; loaded
#                      automatically by lit FIRST because lit searches upward
#                      from the build tree. Its job: inject build-time paths
#                      (tool dirs, build mode) that static source cannot know.
#
#   lit.cfg.py (this file) — static source in the SOURCE directory; loaded
#                      SECOND via lit_config.load_config() at the end of
#                      lit.site.cfg.py. Its job: define the test suite
#                      (name, format, suffixes, substitutions).
#
# Attributes guaranteed to exist when this file runs (set by lit.site.cfg.py):
#   config.llvm_tools_dir  — path to FileCheck, not, etc.
#   config.hip_build_dir   — CMAKE_BINARY_DIR
#   config.hip_build_mode  — "Debug" or "Release" (resolved at runtime for VS)

import os
import lit.formats
import lit.llvm

# ruff: noqa: F821  (config/lit_config injected by lit framework)

config.name = "MorphizenMLIR"
config.test_format = lit.formats.ShTest(execute_external=False)
config.suffixes = [".mlir"]
config.test_source_root = os.path.dirname(__file__)
config.test_exec_root = config.test_source_root

# Correct llvm_tools_dir for multi-config generators BEFORE LLVMConfig runs.
# LLVMConfig.__init__ -> use_default_substitutions registers FileCheck/not/count
# against config.llvm_tools_dir immediately (and substitutions are first-wins),
# so the path must be right here, not patched afterwards. LLVM_TOOLS_BINARY_DIR
# (from cmake) is <llvm-build>/bin, but a Visual Studio multi-config build emits
# the tools under <llvm-build>/<mode>/bin (e.g. .../Release/bin) -- the mode
# segment goes BEFORE bin, not after. Rewrite <...>/bin -> <...>/<mode>/bin when
# that exists; fall back to the bare dir (Ninja single-config + prebuilt-prefix,
# where the tools sit directly in bin).
_llvm_parent, _llvm_leaf = os.path.split(config.llvm_tools_dir.rstrip("/\\"))
_llvm_mode_dir = os.path.join(_llvm_parent, config.hip_build_mode, _llvm_leaf)
if os.path.isdir(_llvm_mode_dir):
    config.llvm_tools_dir = _llvm_mode_dir

# Initialize LLVMConfig using llvm_tools_dir from lit.site.cfg.py.
# This sets up PATH and enables add_tool_substitutions / with_environment.
llvm_config = lit.llvm.config.LLVMConfig(lit_config, config)

# Locate hip tools. Search order:
#   1. <build>/tools/hip-mlir-opt/<mode>/  (VS multi-config layout)
#   2. <build>/tools/hip-mlir-opt/         (Ninja single-config layout)
#   3. <build>/bin/<mode>
#   4. <build>/bin
hip_tool_search = [
    os.path.join(config.hip_build_dir, "tools", "hip-mlir-opt", config.hip_build_mode),
    os.path.join(config.hip_build_dir, "tools", "hip-mlir-opt"),
    os.path.join(config.hip_build_dir, "bin", config.hip_build_mode),
    os.path.join(config.hip_build_dir, "bin"),
]
hip_tools_dirs = [d for d in hip_tool_search if os.path.isdir(d)]

# hip-compiler may live in a separate directory from hip-mlir-opt
for hip_compile_candidate in [
    os.path.join(config.hip_build_dir, "tools", "hip-compiler", config.hip_build_mode),
    os.path.join(config.hip_build_dir, "tools", "hip-compiler"),
]:
    if (
        os.path.isdir(hip_compile_candidate)
        and hip_compile_candidate not in hip_tools_dirs
    ):
        hip_tools_dirs.append(hip_compile_candidate)

if not hip_tools_dirs:
    hip_tools_dirs = [os.path.join(config.hip_build_dir, "bin")]

llvm_config.with_environment("PATH", hip_tools_dirs, append_path=True)

tools = [
    "hip-mlir-opt",
    "hip-compiler",
    "FileCheck",
    "not",
]
llvm_config.add_tool_substitutions(tools, hip_tools_dirs + [config.llvm_tools_dir])

# Sample plugin DLL substitution.
#
# %hip-ep-sample-plugin resolves to the absolute path of the in-tree
# sample plugin built by test/plugin/sample_plugin/CMakeLists.txt.
# Tests that exercise the public plugin ABI (HIP_EP_PLUGINS) point
# at this path so the cross-DLL load path is covered in CI without
# any external artefact.
plugin_search_dirs = [
    os.path.join(config.hip_build_dir, "test", "plugin", "sample_plugin",
                 config.hip_build_mode),
    os.path.join(config.hip_build_dir, "test", "plugin", "sample_plugin"),
]
plugin_filename = "hip_ep_sample_plugin.dll" if os.name == "nt" else \
                  "hip_ep_sample_plugin.so"
sample_plugin_path = ""
for d in plugin_search_dirs:
    candidate = os.path.join(d, plugin_filename)
    if os.path.isfile(candidate):
        sample_plugin_path = candidate
        break
if not sample_plugin_path:
    # Fall back to the first candidate so the substitution string
    # exists; the test will fail with an obvious "plugin not found"
    # error from HIP_EP_PLUGINS rather than a missing-substitution
    # LIT error.
    sample_plugin_path = os.path.join(plugin_search_dirs[0], plugin_filename)
config.substitutions.append(("%hip-ep-sample-plugin",
                             sample_plugin_path.replace("\\", "/")))
