# -*- Python -*-
#
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
#

# LIT two-file config pattern (from lit's point of view):
#
#   lit.site.cfg.py  — generated by CMake into the BUILD directory; loaded
#                      automatically by lit FIRST because lit searches upward
#                      from the build tree. Its job: inject build-time paths
#                      (tool dirs, build mode) that static source cannot know.
#
#   lit.cfg.py (this file) — static source in the SOURCE directory; loaded
#                      SECOND via lit_config.load_config() at the end of
#                      lit.site.cfg.py. Its job: define the test suite
#                      (name, format, suffixes, substitutions).
#
# Attributes guaranteed to exist when this file runs (set by lit.site.cfg.py):
#   config.llvm_tools_dir  — path to FileCheck, not, etc.
#   config.hip_build_dir   — CMAKE_BINARY_DIR
#   config.hip_build_mode  — "Debug" or "Release" (resolved at runtime for VS)

import os
import lit.formats
import lit.llvm

# ruff: noqa: F821  (config/lit_config injected by lit framework)

config.name = "MorphizenMLIR"
config.test_format = lit.formats.ShTest(execute_external=False)
config.suffixes = [".mlir"]
config.test_source_root = os.path.dirname(__file__)
config.test_exec_root = config.test_source_root

# Initialize LLVMConfig using llvm_tools_dir from lit.site.cfg.py.
# This sets up PATH and enables add_tool_substitutions / with_environment.
llvm_config = lit.llvm.config.LLVMConfig(lit_config, config)

# Locate hip tools. Search order:
#   1. <build>/tools/hip-mlir-opt/<mode>/  (VS multi-config layout)
#   2. <build>/tools/hip-mlir-opt/         (Ninja single-config layout)
#   3. <build>/bin/<mode>
#   4. <build>/bin
hip_tool_search = [
    os.path.join(config.hip_build_dir, "tools", "hip-mlir-opt", config.hip_build_mode),
    os.path.join(config.hip_build_dir, "tools", "hip-mlir-opt"),
    os.path.join(config.hip_build_dir, "bin", config.hip_build_mode),
    os.path.join(config.hip_build_dir, "bin"),
]
hip_tools_dirs = [d for d in hip_tool_search if os.path.isdir(d)]

# hip-compiler may live in a separate directory from hip-mlir-opt
for hip_compile_candidate in [
    os.path.join(config.hip_build_dir, "tools", "hip-compiler", config.hip_build_mode),
    os.path.join(config.hip_build_dir, "tools", "hip-compiler"),
]:
    if (
        os.path.isdir(hip_compile_candidate)
        and hip_compile_candidate not in hip_tools_dirs
    ):
        hip_tools_dirs.append(hip_compile_candidate)

if not hip_tools_dirs:
    hip_tools_dirs = [os.path.join(config.hip_build_dir, "bin")]

llvm_config.with_environment("PATH", hip_tools_dirs, append_path=True)

tools = [
    "hip-mlir-opt",
    "hip-compiler",
    "FileCheck",
    "not",
]
llvm_config.add_tool_substitutions(tools, hip_tools_dirs + [config.llvm_tools_dir])

# Plugin feature + substitutions.
# The `hip_plugins` feature is enabled only when both plugin .so files exist
# (i.e. the build was configured with -DBUILD_HIP_PLUGINS=ON and compiled).
# Tests using `// REQUIRES: hip_plugins` are UNSUPPORTED (not failing) in the
# default BUILD_HIP_PLUGINS=OFF lane.
# Resolve %(build_mode)s placeholder (same as hip_build_mode above).
def _resolve(path):
    try:
        return path % lit_config.params if path else path
    except KeyError:
        return path % {"build_mode": config.hip_build_mode} if path else path

_fusion_plugin     = _resolve(getattr(config, "hip_fusion_plugin", ""))
_fusion_plugin_nobuf = _resolve(getattr(config, "hip_fusion_plugin_nobuf", ""))

if _fusion_plugin and os.path.exists(_fusion_plugin) \
        and _fusion_plugin_nobuf and os.path.exists(_fusion_plugin_nobuf):
    config.available_features.add("hip_plugins")
    # Register the longer name first so lit doesn't expand %hip_fusion_plugin
    # as a prefix of %hip_fusion_plugin_nobuf during substitution.
    config.substitutions.append(("%hip_fusion_plugin_nobuf", _fusion_plugin_nobuf))
    config.substitutions.append(("%hip_fusion_plugin",      _fusion_plugin))
