(define (print-operation op-name num-operands num-results generic-form)
  (display "Operation: \"")
  (display op-name)
  (display "\"\n")
  (display "  Operands: ")
  (display num-operands)
  (display "\n")
  (display "  Results: ")
  (display num-results)
  (display "\n")
  (display "  Generic form: ")
  (display generic-form)
  (display "\n\n"))
