// Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
// Licensed under the MIT License.
syntax = "proto3";
package hipdnn;

message TensorShape {
  repeated int64 dims = 1;
}

message HipdnnParamProto {
  string op_type = 1;
  string version = 2;
  
  // Shapes
  repeated TensorShape input_shapes = 3;
  repeated TensorShape output_shapes = 4;
  
  // Data types (ONNX element types)
  repeated int32 input_data_types = 5;
  repeated int32 output_data_types = 6;
  
  // Conv attributes
  repeated int64 pads = 7;
  repeated int64 strides = 8;
  repeated int64 dilations = 9;
  int64 group = 10;
  bool has_bias = 11;
}
