##
# ** Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
# ** Licensed under the MIT License.
##
set(MORPHIZEN_E2E_TESTS_PROTO_FILES
  morphizen-e2e-test/test_case_config.proto
)
set(MORPHIZEN_E2E_TESTS_PROTO_SRCS "")
set(MORPHIZEN_E2E_TESTS_PROTO_HDRS "")
set(Protobuf_USE_STATIC_LIBS ON)
if(NOT TARGET protobuf::libprotobuf OR NOT TARGET protobuf::protoc)
  find_package(Protobuf CONFIG REQUIRED)
endif()
if (NOT EXISTS ${CMAKE_CURRENT_BINARY_DIR}/e2e_config_proto)
  file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/e2e_config_proto)
endif()
foreach(MORPHIZEN_E2E_TESTS_PROTO_FILE ${MORPHIZEN_E2E_TESTS_PROTO_FILES})
  get_filename_component(MORPHIZEN_E2E_TESTS_PROTO_FILE_NAME ${MORPHIZEN_E2E_TESTS_PROTO_FILE} NAME_WE)
  message(STATUS "generating proto --- ${MORPHIZEN_E2E_TESTS_PROTO_FILE_NAME}.pb.cc ${MORPHIZEN_E2E_TESTS_PROTO_FILE_NAME}.pb.h")
  add_custom_command(
    OUTPUT
      ${CMAKE_CURRENT_BINARY_DIR}/e2e_config_proto/${MORPHIZEN_E2E_TESTS_PROTO_FILE_NAME}.pb.cc
      ${CMAKE_CURRENT_BINARY_DIR}/e2e_config_proto/${MORPHIZEN_E2E_TESTS_PROTO_FILE_NAME}.pb.h
    COMMAND protobuf::protoc
    ARGS
    --cpp_out=${CMAKE_CURRENT_BINARY_DIR}/e2e_config_proto
    -I ${CMAKE_CURRENT_SOURCE_DIR}/morphizen-e2e-test
    ${CMAKE_CURRENT_SOURCE_DIR}/${MORPHIZEN_E2E_TESTS_PROTO_FILE}
    DEPENDS ${MORPHIZEN_E2E_TESTS_PROTO_FILE})
  list(APPEND MORPHIZEN_E2E_TESTS_PROTO_SRCS ${CMAKE_CURRENT_BINARY_DIR}/e2e_config_proto/${MORPHIZEN_E2E_TESTS_PROTO_FILE_NAME}.pb.cc)
  list(APPEND MORPHIZEN_E2E_TESTS_PROTO_HDRS ${CMAKE_CURRENT_BINARY_DIR}/e2e_config_proto/${MORPHIZEN_E2E_TESTS_PROTO_FILE_NAME}.pb.h)
endforeach(MORPHIZEN_E2E_TESTS_PROTO_FILE ${MORPHIZEN_E2E_TESTS_PROTO_FILES})
