/*
 * Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
 * Licensed under the MIT License.
 */
#include "morphizen/onnx_schema.hpp"

#include <mutex>

// generated by onnx_schema_json_binary.hpp.py
#include "./binary/onnx_schema_json_binary.hpp"

namespace morphizen {

using OpSchemaRegistry = ONNX_NAMESPACE::OpSchemaRegistry;

namespace {

// Helper function to register schemas from generated C++ code
void LoadSchemasFromGeneratedCode() {
  static std::once_flag initialized;
  std::call_once(initialized, []() {
    // Call the generated registration function
    generated_schemas::RegisterAllSchemas();
  });
}

} //  namespace

#define ENSURE_INITIALIZAED                                                    \
  do {                                                                         \
    LoadSchemasFromGeneratedCode();                                            \
  } while (0)

const OpSchema* GetOpSchema(const std::string& key, const std::string& domain) {
  ENSURE_INITIALIZAED;
  return OpSchemaRegistry::Schema(key, domain);
}

} // namespace morphizen
