/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 * Licensed under the MIT License.
 */
//===-- Passes.td - OnnxToHip conversion pass definitions -*- tablegen -*-===//
//
// HipAddContextArgPass has been moved to include/hip/Dialect/Transforms/Passes.td
//
//===----------------------------------------------------------------------===//

#ifndef ONNXTOHIP_PASSES
#define ONNXTOHIP_PASSES

include "mlir/Pass/PassBase.td"

#endif // ONNXTOHIP_PASSES
