/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 * Licensed under the MIT License.
 */

//===- module_registry.h - Op Module Registry --------------------------*-===//
//
// INTERNAL HEADER - Not part of public ABI
//
// Each operator that needs persistent per-session state ("op module")
// registers a spec with the framework at static-init time and gets back a
// stable integer slot id. The accessor function (generated by the
// HIPDNN_OP_MODULE macro) then does an O(1) array lookup + cast on every
// wrap_* call.
//
// Lifecycle:
//   * init_fn          - called lazily on first access per RuntimeState
//                        session.
//   * destroy_fn       - called from hipdnn_ep_state_cleanup on every
//                        populated slot, in reverse registration order.
//   * begin_compute_fn - called from hipdnn_ep_runtime_begin_compute on
//                        every populated slot whose spec defines it
//                        (nullable). Single Compute() hook for per-forward
//                        cache invalidation.
//   * end_compute_fn   - reserved for future per-Compute() flush (nullable).
//   * mem_bytes_fn     - reports buffer footprint for HIPDNN_EP_DUMP_STATE
//                        (nullable). Stage 5.
//
// Steady-state invariant:
//   After the first access on a given session, op_module_get does:
//     1. range check on slot_id (one compare)
//     2. load reg->slots[slot_id].state_ptr (one load)
//     3. branch on null (one branch)
//   No mutex, no allocation, no string operation. The per-Compute()
//   begin_compute loop is similarly lock-free: function pointers and state
//   pointers are cached in the slot entry on first access, so the iteration
//   does not call into the process-global spec table.
//
// Usage (covers ~95% of ops):
//
//   namespace {
//   struct MyOpState {
//     SomeCache cache;
//     explicit MyOpState(RuntimeState *) {}
//     ~MyOpState() = default;
//     // Optional:
//     //   void begin_compute(RuntimeState *);
//     //   void end_compute(RuntimeState *);
//     //   size_t mem_bytes() const;
//   };
//   HIPDNN_OP_MODULE(my_op_module, "my_op", MyOpState);
//   }
//
//   int wrap_my_op(RuntimeState *state, ...) {
//     auto *st = my_op_module(state);
//     st->cache.find(...);
//   }
//
//===---------------------------------------------------------------------===//

#ifndef HIPDNN_EP_MODULE_REGISTRY_H
#define HIPDNN_EP_MODULE_REGISTRY_H

#include <cstddef>
#include <type_traits>

// Opaque to the registry layer; only passed through to user callbacks.
struct RuntimeState;

namespace hipdnn_ep {

// Forward decl; full definition is in module_registry.cpp.
struct ModuleRegistry;

// C-style function pointers so OpModuleSpec is trivially copyable / safe to
// hand a pointer to across the bitcode / native boundary.
using OpInitFn = void *(*)(RuntimeState *);
using OpDestroyFn = void (*)(void *);
using OpBeginComputeFn = void (*)(void *, RuntimeState *);
using OpEndComputeFn = void (*)(void *, RuntimeState *);
using OpMemBytesFn = size_t (*)(void *);

struct OpModuleSpec {
  const char *name = nullptr;
  OpInitFn init_fn = nullptr;
  OpDestroyFn destroy_fn = nullptr;
  OpBeginComputeFn begin_compute_fn = nullptr;
  OpEndComputeFn end_compute_fn = nullptr;
  OpMemBytesFn mem_bytes_fn = nullptr;
};

//===------------------- Process-global registry -------------------------===//
//
// register_op_module is called once per (op, translation unit) from a
// function-local static inside the accessor that HIPDNN_OP_MODULE generates.
// Slot ids are assigned in registration order and are stable for the
// lifetime of the process.
//
// Each linked-in copy of the runtime (bitcode -> model.dll, or native ->
// test binary) has its own process-global table. The table grows but never
// shrinks; deregistration is not supported.

// Register an op-module spec. Returns a stable, non-negative slot id.
// Aborts on duplicate name or missing required fields (name / init_fn /
// destroy_fn). `spec` must remain valid for the process lifetime --
// typically a function-local static inside the accessor.
int register_op_module(const OpModuleSpec *spec);

// Look up a registered spec by slot id. Returns nullptr if out of range.
// Used by module_registry_create() / module_registry_destroy() on the cold
// path; the hot path bypasses this and uses cached per-slot fn pointers.
const OpModuleSpec *get_op_module_spec(int slot_id);

// Current number of registered specs.
int op_module_count();

//===-------------------- Per-RuntimeState slots -------------------------===//

// Construct an empty module registry. Slots are populated lazily by
// op_module_get on first access; no allocation happens here beyond the
// ModuleRegistry struct itself.
ModuleRegistry *module_registry_create();

// Destroy every populated slot via its spec->destroy_fn, in reverse
// registration order, then free the registry. Safe to pass nullptr.
void module_registry_destroy(ModuleRegistry *reg);

// Iterate every populated slot whose cached begin_compute fn is non-null and
// invoke it. Called from hipdnn_ep_runtime_begin_compute at the top of every
// Compute(). Lock-free; iterates a tiny std::vector of cached fn-pointer /
// state-pointer pairs.
void module_registry_begin_compute(ModuleRegistry *reg, RuntimeState *state);

// Print one line per populated slot to stderr:
//
//   [HIPDNN_EP_DUMP_STATE] slot=<id> name='<name>' mem_bytes=<N or "?">
//
// "?" appears when the module did not define a `mem_bytes() const` method.
// Called from hipdnn_ep_state_cleanup when HIPDNN_EP_DUMP_STATE=1 is set in
// the environment. Compatibility: this is the official observability hook
// for the module system -- adding `size_t mem_bytes() const` to any state
// type immediately makes it appear in the dump with no other plumbing.
void module_registry_dump(ModuleRegistry *reg);

// O(1) accessor: returns the cached slot state pointer, lazily invoking
// spec->init_fn on miss. Returns nullptr if reg/slot_id is invalid, or if
// init_fn fails.
//
// Hot path (after warmup): one bounds compare + one load + one null-branch.
// Cold path (first access): one vector resize + spec lookup + init_fn call.
void *op_module_get(ModuleRegistry *reg, RuntimeState *state, int slot_id);

// Glue: fetch the ModuleRegistry pointer out of RuntimeState. Implemented
// in hipdnn_ep_runtime_state.cpp where RuntimeState's layout is visible.
// Declared here so the HIPDNN_OP_MODULE macro can inline-call it without
// the user having to include runtime_state_internal.h (which would expose
// every other internal field).
ModuleRegistry *get_module_registry(RuntimeState *state);

//===------------------- HIPDNN_OP_MODULE helpers ------------------------===//
//
// SFINAE detectors for the optional hooks. Each maps to false_type when the
// hook is absent and true_type otherwise. Used by make_op_module_spec to
// synthesize trampolines only for the hooks the user defined.

template <typename T, typename = void>
struct has_begin_compute_ : std::false_type {};

template <typename T>
struct has_begin_compute_<
    T, std::void_t<decltype(std::declval<T &>().begin_compute(
           std::declval<RuntimeState *>()))>> : std::true_type {};

template <typename T, typename = void>
struct has_end_compute_ : std::false_type {};

template <typename T>
struct has_end_compute_<T, std::void_t<decltype(std::declval<T &>().end_compute(
                               std::declval<RuntimeState *>()))>>
    : std::true_type {};

template <typename T, typename = void>
struct has_mem_bytes_ : std::false_type {};

template <typename T>
struct has_mem_bytes_<
    T, std::void_t<decltype(std::declval<const T &>().mem_bytes())>>
    : std::true_type {};

// Build an OpModuleSpec for the state type T. Required: T must be
// constructible from a RuntimeState*. Optional methods are detected by
// SFINAE; absent methods leave the corresponding fn pointer null.
template <typename T>
inline OpModuleSpec make_op_module_spec(const char *name) {
  OpModuleSpec spec{};
  spec.name = name;
  spec.init_fn =
      +[](RuntimeState *s) -> void * { return static_cast<void *>(new T(s)); };
  spec.destroy_fn = +[](void *p) { delete static_cast<T *>(p); };
  if constexpr (has_begin_compute_<T>::value) {
    spec.begin_compute_fn = +[](void *p, RuntimeState *s) {
      static_cast<T *>(p)->begin_compute(s);
    };
  }
  if constexpr (has_end_compute_<T>::value) {
    spec.end_compute_fn =
        +[](void *p, RuntimeState *s) { static_cast<T *>(p)->end_compute(s); };
  }
  if constexpr (has_mem_bytes_<T>::value) {
    spec.mem_bytes_fn = +[](void *p) -> size_t {
      return static_cast<const T *>(p)->mem_bytes();
    };
  }
  return spec;
}

} // namespace hipdnn_ep

//===---------------------- HIPDNN_OP_MODULE macro -----------------------===//
//
// Declares a strongly-typed accessor for an op module. Two function-local
// statics:
//   1. The OpModuleSpec (auto-built from STATE_T at compile time via
//      make_op_module_spec) -- one per translation unit, address stable.
//   2. The slot id returned by register_op_module on first call -- one per
//      translation unit.
//
// C++11 guarantees both statics are initialized exactly once (thread-safe).
// On subsequent calls only the final cast + array lookup runs.
//
// Place the macro at namespace scope (typically anonymous namespace inside
// the .cpp), passing:
//   ACCESSOR : name of the generated function, e.g. `causal_conv_module`.
//   NAME     : unique string id used for logs / dump / dedup-abort.
//   STATE_T  : your <Op>State type; constructible from RuntimeState*.

#define HIPDNN_OP_MODULE(ACCESSOR, NAME, STATE_T)                              \
  static STATE_T *ACCESSOR(::RuntimeState *state) {                            \
    static const ::hipdnn_ep::OpModuleSpec hipdnn_ep_module_spec_ =            \
        ::hipdnn_ep::make_op_module_spec<STATE_T>(NAME);                       \
    static const int hipdnn_ep_module_slot_ =                                  \
        ::hipdnn_ep::register_op_module(&hipdnn_ep_module_spec_);              \
    return static_cast<STATE_T *>(                                             \
        ::hipdnn_ep::op_module_get(::hipdnn_ep::get_module_registry(state),    \
                                   state, hipdnn_ep_module_slot_));            \
  }

#endif // HIPDNN_EP_MODULE_REGISTRY_H
