# AUTO-GENERATED by tools/hip-op-registry-gen.py -- DO NOT EDIT
#
# Scanned 26 TorchToHip patterns from C++ source
#
GEN_VERSION = "907d60541396"

# Ops discovered from C++ RewritePattern registrations
GEN_OPS = {
    "torch.aten.add.Tensor": "elementwise",
    "torch.aten.bmm": "matmul",
    "torch.aten.cat.default": "shape",
    "torch.aten.conv2d": "conv",
    "torch.aten.div.Tensor": "misc",
    "torch.aten.index_select": "index",
    "torch.aten.linear": "matmul",
    "torch.aten.matmul": "matmul",
    "torch.aten.matmul_nbits": "matmul",
    "torch.aten.mm": "matmul",
    "torch.aten.mul.Tensor": "elementwise",
    "torch.aten.qmoe": "quantized",
    "torch.aten.reshape": "shape",
    "torch.aten.rms_norm": "norm",
    "torch.aten.scaled_dot_product_attention": "attention",
    "torch.aten.sigmoid": "activation",
    "torch.aten.silu": "activation",
    "torch.aten.slice.Tensor": "shape",
    "torch.aten.softmax.int": "activation",
    "torch.aten.split.Tensor": "misc",
    "torch.aten.squeeze.dim": "shape",
    "torch.aten.sub.Tensor": "elementwise",
    "torch.aten.sum.dim_IntList": "reduction",
    "torch.aten.to.dtype": "cast",
    "torch.aten.transpose.int": "shape",
    "torch.aten.unsqueeze": "shape",
}
