#!/usr/bin/env python3
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
"""Embed a binary HSACO file into a C header as a static byte array.

Usage:
  python embed_hsaco.py <input.hsaco> <output.h> <symbol_name>

The header declares:
  static const unsigned char <symbol_name>[]      = { 0x.., ... };
  static const unsigned long <symbol_name>_size   = <bytes>;

DRAFT-PR shape: rerun manually after rebuilding the HSACO via ck_dsl. A
follow-up can promote this to a CMake `add_custom_command` so the generation
runs at build time.
"""
from __future__ import annotations

import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    inp = Path(sys.argv[1])
    out = Path(sys.argv[2])
    sym = sys.argv[3]
    blob = inp.read_bytes()

    lines = [
        "// Auto-generated by scripts/embed_hsaco.py. DO NOT EDIT.",
        f"// Source: {inp.name} ({len(blob)} bytes)",
        "#pragma once",
        "",
        f"static const unsigned char {sym}[] = {{",
    ]
    # 16 bytes per line.
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_bytes},")
    lines.append("};")
    lines.append(f"static const unsigned long {sym}_size = {len(blob)};")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"Wrote {out} ({len(blob)} bytes embedded as {sym})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
