#!/usr/bin/env python3
#
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
#
"""
Auto-generate LIT tests for TorchToHip conversion patterns.

Reads the op registry and generates one MLIR test per op that has
a test_shapes specification. Each test verifies the torch op is
converted to the expected HIP dialect op.

Usage:
    python tools/gen_torch_lit_tests.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))

from hip_torch.op_registry import OP_REGISTRY

OUTPUT_DIR = (
    Path(__file__).parent.parent
    / "test"
    / "lit"
    / "Conversion"
    / "torch-to-hip"
    / "gen"
)


def parse_shape_spec(spec: str):
    """Parse 'AxBxDTYPE,CxDxDTYPE->ExFxDTYPE' into input/output types."""
    if not spec or "->" not in spec:
        return None
    inputs_str, output_str = spec.split("->")
    inputs = inputs_str.split(",")

    def to_mlir_type(s):
        s = s.strip()
        parts = s.split("x")
        dtype = parts[-1]
        dims = "x".join(parts[:-1])
        if dims:
            return f"tensor<{dims}x{dtype}>"
        return f"tensor<{dtype}>"

    return [to_mlir_type(i) for i in inputs], to_mlir_type(output_str)


def gen_constant_args(op_name: str, info) -> list:
    """Generate constant arg MLIR for ops that need them."""
    args = []
    if "add" in op_name or "sub" in op_name:
        args.append(
            (
                '    %alpha = "torch.constant.int"() {value = 1 : i64} : () -> !torch.int',
                "%alpha",
                "!torch.int",
            )
        )
    if "softmax" in op_name:
        args.append(
            (
                '    %dim = "torch.constant.int"() {value = -1 : i64} : () -> !torch.int',
                "%dim",
                "!torch.int",
            )
        )
        args.append(
            (
                '    %none = "torch.constant.none"() : () -> !torch.none',
                "%none",
                "!torch.none",
            )
        )
    if op_name == "torch.aten.rms_norm":
        args.append(
            (
                '    %eps = "torch.constant.float"() {value = 1.000000e-06 : f64} : () -> !torch.float',
                "%eps",
                "!torch.float",
            )
        )
        last_dim = "32"  # default
        args.append(
            (
                f'    %dim = "torch.constant.int"() {{value = {last_dim} : i64}} : () -> !torch.int',
                "%dim",
                "!torch.int",
            )
        )
        args.append(
            (
                '    %shape = "torch.prim.ListConstruct"(%dim) : (!torch.int) -> !torch.list<int>',
                "%shape",
                "!torch.list<int>",
            )
        )
    if op_name == "torch.aten.linear":
        args.append(
            (
                '    %none = "torch.constant.none"() : () -> !torch.none',
                "%none",
                "!torch.none",
            )
        )
    return args


def generate_test(op_name: str, info) -> str:
    """Generate a LIT test for one op."""
    parsed = parse_shape_spec(info.test_shapes)
    if parsed is None:
        return ""

    input_types, output_type = parsed
    check_op = info.hip_op or "hip."
    safe_name = op_name.replace(".", "_").replace("torch_aten_", "")

    lines = [
        "// AUTO-GENERATED by tools/gen_torch_lit_tests.py -- DO NOT EDIT",
        f"// Tests: {op_name} -> {check_op}",
        "// RUN: hip-mlir-opt %s --hip-add-context-arg --convert-torch-to-hip | FileCheck %s",
        "",
    ]

    # Function signature
    arg_strs = [f"%arg{i}: {t}" for i, t in enumerate(input_types)]

    # Add constant args
    const_args = gen_constant_args(op_name, info)

    lines.append(f"// CHECK-LABEL: func.func @test_{safe_name}")
    if check_op and check_op != "hip.":
        lines.append(f"// CHECK: {check_op}")
    lines.append(f"// CHECK-NOT: {op_name}")

    lines.append(
        f"func.func @test_{safe_name}({', '.join(arg_strs)}) -> {output_type} {{"
    )

    # Emit constant definitions
    for const_line, _, _ in const_args:
        lines.append(const_line)

    # Build op call args
    op_args = [f"%arg{i}" for i in range(len(input_types))]
    for _, ref, _ in const_args:
        op_args.append(ref)

    op_arg_types = list(input_types)
    for _, _, t in const_args:
        op_arg_types.append(t)

    lines.append(
        f'    %result = "{op_name}"({", ".join(op_args)}) : '
        f"({', '.join(op_arg_types)}) -> {output_type}"
    )
    lines.append(f"    return %result : {output_type}")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    generated = 0
    for op_name, info in sorted(OP_REGISTRY.items()):
        if not info.test_shapes or info.free or not info.hip_op:
            continue

        test_content = generate_test(op_name, info)
        if not test_content:
            continue

        safe_name = op_name.replace(".", "_").replace("torch_aten_", "")
        test_file = OUTPUT_DIR / f"test_{safe_name}.mlir"
        test_file.write_text(test_content, encoding="utf-8")
        generated += 1

    print(f"Generated {generated} LIT tests in {OUTPUT_DIR}")

    # List generated files
    for f in sorted(OUTPUT_DIR.glob("*.mlir")):
        print(f"  {f.name}")


if __name__ == "__main__":
    main()
