#!/usr/bin/env python3
#
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
#
"""
Auto-generate the Python op registry from C++ TorchToHip pattern files.

Scans lib/Conversion/TorchToHip/*.cpp for RewritePattern constructor calls
that contain the torch op name string, and generates scripts/hip_torch/op_registry.py.

Usage:
    python tools/hip-op-registry-gen.py [--dry-run]
"""

import argparse
import hashlib
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
TORCH_TO_HIP_DIR = PROJECT_ROOT / "lib" / "Conversion" / "TorchToHip"
OUTPUT_FILE = PROJECT_ROOT / "scripts" / "hip_torch" / "_gen_ops.py"


def scan_cpp_patterns() -> list:
    """Scan C++ files for RewritePattern("torch.aten.*") registrations."""
    ops = []
    pattern = re.compile(r'RewritePattern\("(torch\.aten\.[^"]+)"')

    for cpp_file in sorted(TORCH_TO_HIP_DIR.glob("*.cpp")):
        if cpp_file.name in ("TorchToHip.cpp",):
            continue  # orchestrator, not patterns
        text = cpp_file.read_text(encoding="utf-8", errors="ignore")
        for match in pattern.finditer(text):
            op_name = match.group(1)
            # Infer category from filename
            fname = cpp_file.stem.replace("Conversion", "").lower()
            category = _infer_category(fname)
            ops.append(
                {
                    "name": op_name,
                    "category": category,
                    "source": cpp_file.name,
                }
            )
    return ops


def _infer_category(filename: str) -> str:
    """Infer op category from conversion filename."""
    mapping = {
        "elementwise": "elementwise",
        "matmul": "matmul",
        "matmulnbits": "quantized",
        "activation": "activation",
        "norm": "norm",
        "gqa": "attention",
        "qmoe": "quantized",
        "cast": "cast",
        "gather": "index",
        "reduce": "reduction",
        "reshape": "shape",
        "transpose": "shape",
        "slicecat": "shape",
        "conv": "conv",
        "misc": "misc",
    }
    for key, cat in mapping.items():
        if key in filename:
            return cat
    return "unknown"


def generate_report(ops: list) -> str:
    """Generate a report of discovered ops."""
    lines = [
        "# Auto-discovered TorchToHip patterns",
        f"# Scanned: {TORCH_TO_HIP_DIR}",
        f"# Found: {len(ops)} patterns",
        "",
    ]
    by_category = {}
    for op in ops:
        by_category.setdefault(op["category"], []).append(op)

    for cat in sorted(by_category):
        lines.append(f"## {cat} ({len(by_category[cat])} ops)")
        for op in sorted(by_category[cat], key=lambda x: x["name"]):
            lines.append(f"  {op['name']:45s}  [{op['source']}]")
        lines.append("")

    return "\n".join(lines)


def generate_python(ops: list) -> str:
    """Generate the _gen_ops.py module."""
    version = hashlib.sha256(str(sorted(o["name"] for o in ops)).encode()).hexdigest()[
        :12
    ]
    lines = [
        "# AUTO-GENERATED by tools/hip-op-registry-gen.py -- DO NOT EDIT",
        "#",
        f"# Scanned {len(ops)} TorchToHip patterns from C++ source",
        "#",
        f'GEN_VERSION = "{version}"',
        "",
        "# Ops discovered from C++ RewritePattern registrations",
        "GEN_OPS = {",
    ]
    for op in sorted(ops, key=lambda x: x["name"]):
        lines.append(f'    "{op["name"]}": "{op["category"]}",')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Print report only")
    args = parser.parse_args()

    ops = scan_cpp_patterns()

    if args.dry_run:
        print(generate_report(ops))
        print(f"\nTotal: {len(ops)} patterns discovered")
        return

    # Generate
    content = generate_python(ops)
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE} with {len(ops)} ops")
    print(generate_report(ops))


if __name__ == "__main__":
    main()
