message(STATUS "download ${URL} to ${FILE}")
set(args "${URL}" "${FILE}")
if(EXPECTED_MD5)
    list(APPEND args "EXPECTED_MD5" "${EXPECTED_MD5}")
endif()
file(DOWNLOAD ${args})
if(PATCH_FILES)
    foreach(patch_file ${PATCH_FILES})
        execute_process(COMMAND "${Patch_EXECUTABLE}" -i "${patch_file}" -p1)
    endforeach()
endif()
