
option(morphizen_ENABLE_UNIT_TEST "enable vaip unit test or not" ON)
#
# to build MorphiZen, we need to download source code of onnxruntime
# and build it along with MorphiZen
#
set(ONNXRUNTIME_SOURCE_TREE_DIR "${CMAKE_SOURCE_DIR}/../onnxruntime" CACHE PATH "Path to the root of the ONNX Runtime source tree")
#
# it is possible to emebed xclbin files in the binary, assume the xclbin files are in the directory
#
set(VAIP_XCLBIN_DIR ${CMAKE_SOURCE_DIR}/../vaip_xclbin CACHE PATH "Path to the directory containing xclbin files")
#
# it is possible to embed json files in the binary, assume the json files are in the directory
set(VAIP_JSON_CONFIG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/vaip-core/etc/vaip_config.json" CACHE FILEPATH "Path to the file containing vaip_config.json files")

# it is possible to embed version_info.txt files in the binary, assume the version_info.txt files are in the directory
# version_info.txt files are generated by the script vaip_version_info.hpp.inc.py
# `#` is used as a comment in the version_info.txt files
# each line in the version_info.txt files contains three columns separated by `;'
# the first column of the version_info.txt files is the component name
# the second column of the version_info.txt files is the git commit hash
# the third column of the version_info.txt files is the version id
# see etc/version_info.txt as an example
set(VAIP_VERSEION_INFO_FILE "${CMAKE_CURRENT_SOURCE_DIR}/vaip-core/etc/version_info.txt" CACHE FILEPATH "Path to the file containing version_info.txt files")

#
set(morphizen_OUTPUT_NAME "onnxruntime_vitisai_ep" CACHE STRING "Output name of MorphiZen library")

# print all options
message(STATUS "MorphiZen OPTIONS:")
message(STATUS "  VAIP_XCLBIN_DIR : ${VAIP_XCLBIN_DIR}")
message(STATUS "  ONNX_RUNTIME_SOURCE_TREE_DIR : ${ONNXRUNTIME_SOURCE_TREE_DIR}")
message(STATUS "  VAIP_JSON_CONFIG_FILE : ${VAIP_JSON_CONFIG_FILE}")
message(STATUS "  VAIP_VERSEION_INFO_FILE : ${VAIP_VERSEION_INFO_FILE}")
message(STATUS "  morphizen_OUTPUT_NAME : ${morphizen_OUTPUT_NAME}")
message(STATUS "  morphizen_ENABLE_UNIT_TEST : ${morphizen_ENABLE_UNIT_TEST}")
