##
# ** Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
# ** Licensed under the MIT License.
##


# This file is used to set options for MorphiZen

# MorphiZen options
set(FETCHCONTENT_QUIET FALSE CACHE BOOL "disable download progress")
# enable morphizen-core-dynamic or not. when MorphiZen is built as a standalone library, this option should be ON
# when MorphiZen is built as part of onnxruntime, this option should be OFF
execute_process(
    COMMAND git rev-parse HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE GIT_VERSION_FOUND
  )
set(morphizen_CORE_DYNAMIC_UNIQUE_ID "morphizen-core-dynamic-${GIT_VERSION}" CACHE STRING "the unique name for morphizen-core-dynamic")
if (TARGET onnxruntime_providers_morphizen)
  set(morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC_DEFAULT OFF)
  set(morphizen_WITH_MORPHIZEN_CONFIG_FILE_DEFAULT OFF)
  set(morphizen_ENABLE_UNIT_TEST_DEFAULT OFF)
  set(morphizen_ONNXRUNTIME_MORPHIZEN_EP_TARGET_DEFAULT "onnxruntime_providers_morphizen")
  set(TRIM_CONFIG_DEFAULT ON)
else()
  set(morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC_DEFAULT ON)
  set(morphizen_WITH_MORPHIZEN_CONFIG_FILE_DEFAULT ON)
  set(morphizen_ENABLE_UNIT_TEST_DEFAULT OFF)
  set(morphizen_ONNXRUNTIME_MORPHIZEN_EP_TARGET_DEFAULT ${morphizen_CORE_DYNAMIC_UNIQUE_ID})
  set(TRIM_CONFIG_DEFAULT OFF)
endif()
option(morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC "enable morphizen-core-dynamic or not" ${morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC_DEFAULT})

set(morphizen_ONNXRUNTIME_MORPHIZEN_EP_TARGET ${morphizen_ONNXRUNTIME_MORPHIZEN_EP_TARGET_DEFAULT} CACHE STRING "the name of target whose output name is onnxruntime_morphizen_ep")
# enable morphizen unit test or not
option(morphizen_ENABLE_UNIT_TEST "enable morphizen unit test or not" ${morphizen_ENABLE_UNIT_TEST_DEFAULT})
# enable Boost dependency for executables and unit tests
# Default: ON (backward compatible - existing builds continue to work as before)
# When ON: Enables Boost-dependent executables and Boost::Process unit tests (default behavior)
# When OFF: Builds a lightweight version of MorphiZen without Boost dependency. The following will be disabled:
#   - Executables: morphizen-tar, morphizen-graph-opt, morphizen-onnx-grep, morphizen-pattern-gen
#   - Unit tests that use Boost::Process (tests in test_tar_file.cpp, test_graph.cpp, test_const_data.cpp)
# Components depending on Boost:
#   - Executables (require Boost::Process for subprocess execution):
#     * morphizen-tar (tar/)
#     * morphizen-graph-opt (graph-opt/)
#     * morphizen-onnx-grep (onnx-grep/)
#     * morphizen-pattern-gen (pattern-gen/)
#   - Unit tests (require Boost::Process):
#     * test_tar_file.cpp (unit-test/morphizen/test_tar_file.cpp)
#     * test_graph.cpp (unit-test/morphizen/test_graph.cpp)
#     * test_const_data.cpp (unit-test/morphizen/test_const_data.cpp)
option(morphizen_ENABLE_BOOST "enable Boost dependency for executables and unit tests" OFF)
#
set(MORPHIZEN_EMBEDDED_RESOURCE_PATH "" CACHE PATH "Path to the meta info of embedded resource files")


# morphizen_WITH_MORPHIZEN_CONFIG_FILE = ON if build with default
# config in morphizen-core-dynamic, i.e. onnxruntime_vitisai_ep.dll
# morphizen_WITH_MORPHIZEN_CONFIG_FILE = OFF if morphizen is built as part
# of onnxruntime, the default config is read from a plugin.
option(morphizen_WITH_MORPHIZEN_CONFIG_FILE "build with default morphizen config in morphizen-core-dynamic, i.e. onnxruntime_vitisai_ep.dll" ${morphizen_WITH_MORPHIZEN_CONFIG_FILE_DEFAULT})
#
# it is possible to embed json files in the binary, assume the json files are in the directory
set(MORPHIZEN_JSON_CONFIG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/morphizen-core/etc/morphizen_config.json" CACHE FILEPATH "Path to the file containing morphizen_config.json files")

# it is possible to embed version_info.txt files in the binary, assume the version_info.txt files are in the directory
# version_info.txt files are generated by the script morphizen_version_info.hpp.inc.py
# `#` is used as a comment in the version_info.txt files
# each line in the version_info.txt files contains three columns separated by `;'
# the first column of the version_info.txt files is the component name
# the second column of the version_info.txt files is the git commit hash
# the third column of the version_info.txt files is the version id
# see etc/version_info.txt as an example
set(MORPHIZEN_VERSION_INFO_FILE "${CMAKE_CURRENT_SOURCE_DIR}/morphizen-core/etc/version_info.txt" CACHE FILEPATH "Path to the file containing version_info.txt files")

#
set(morphizen_OUTPUT_NAME "onnxruntime_vitisai_ep" CACHE STRING "Output name of MorphiZen library (using VitisAI name for ORT compatibility)")

## this option is used to trim morphizen_config.json
option(TRIM_CONFIG "trim default morphizen_config.json" "${TRIM_CONFIG_DEFAULT}")
option(morphizen_ENABLE_ORT_BRIDGE "enable onnxruntime bridge" ON)
option(morphizen_ENABLE_ONNX_BACKEND "enable ONNX backend for ORT bridge" OFF)
option(morphizen_ENABLE_MLIR_BACKEND "enable MLIR as a backend of morphizen_ort_api for ORT bridge" ON)
option(morphizen_ENABLE_ONNX_SCHEMA_SUPPORT "enable ONNX schema support for node_with_named_args feature in morphizen-core-static" OFF)
option(morphizen_ENABLE_PATTERN_MATCHING "enable pattern matching library (morphizen-pattern)" ON)
# HIP-backed OrtAllocator + OrtDataTransferImpl in the EP factory: lets
# ORT (and OGA via ORT) place tensors in AMD GPU memory instead of paying
# a per-call host H2D/D2H copy. Requires find_package(hip) from ROCm/TheRock.
#
# Default ON for the production AMD GPU path (~6x speedup on m=16384 LLM
# decode). OFF is kept for onnx-hipdnn-ep's BUILD_MOCK_RUNTIME=ON build,
# which has no ROCm SDK and would fail find_package(hip REQUIRED) -- with
# OFF the EP DLL still builds, the factory just returns errors from its
# CreateAllocator / CreateDataTransfer hooks (mock can't run on GPU anyway).
# The WARNING below catches the footgun if anyone flips it OFF for a
# non-mock reason.
option(morphizen_ENABLE_HIP_GPU_ALLOCATOR "enable hipHostMalloc-based OrtAllocator + DataTransfer in MorphiZen EP factory (requires HIP runtime; the parent project's mock build forces this OFF)" ON)
if(morphizen_ENABLE_ORT_BRIDGE AND NOT morphizen_ENABLE_HIP_GPU_ALLOCATOR)
  message(WARNING
    "morphizen_ENABLE_HIP_GPU_ALLOCATOR=OFF -- the MorphiZen EP factory "
    "will not register a HIP-backed OrtAllocator / OrtDataTransfer, so "
    "downstream consumers (OGA, ORT) will keep tensors in host RAM and "
    "pay full H2D/D2H per inference (~6x slowdown on m=16384 LLM decode). "
    "This is expected for onnx-hipdnn-ep's BUILD_MOCK_RUNTIME=ON path; "
    "any build that actually targets AMD GPU should keep this ON.")
endif()

# Validate backend configuration when ORT bridge is enabled
if(morphizen_ENABLE_ORT_BRIDGE)
  if(NOT morphizen_ENABLE_ONNX_BACKEND AND NOT morphizen_ENABLE_MLIR_BACKEND)
    message(FATAL_ERROR "When morphizen_ENABLE_ORT_BRIDGE is ON, at least one backend must be enabled: morphizen_ENABLE_ONNX_BACKEND or morphizen_ENABLE_MLIR_BACKEND")
  endif()
endif()
# print all options
message(STATUS "MorphiZen OPTIONS:")
message(STATUS "  morphizen_ONNXRUNTIME_MORPHIZEN_EP_TARGET : ${morphizen_ONNXRUNTIME_MORPHIZEN_EP_TARGET}")
message(STATUS "  morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC : ${morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC}")
message(STATUS "  MORPHIZEN_EMBEDDED_RESOURCE_PATH : ${MORPHIZEN_EMBEDDED_RESOURCE_PATH}")
message(STATUS "  morphizen_WITH_MORPHIZEN_CONFIG_FILE : ${morphizen_WITH_MORPHIZEN_CONFIG_FILE}")
message(STATUS "  MORPHIZEN_JSON_CONFIG_FILE : ${MORPHIZEN_JSON_CONFIG_FILE}")
message(STATUS "  MORPHIZEN_VERSION_INFO_FILE : ${MORPHIZEN_VERSION_INFO_FILE}")
message(STATUS "  morphizen_OUTPUT_NAME : ${morphizen_OUTPUT_NAME}")
message(STATUS "  TRIM_CONFIG : ${TRIM_CONFIG}")
message(STATUS "  BUILD_PYTHON : ${BUILD_PYTHON}")
message(STATUS "  morphizen_ENABLE_ORT_BRIDGE : ${morphizen_ENABLE_ORT_BRIDGE}")
message(STATUS "  morphizen_ENABLE_ONNX_BACKEND : ${morphizen_ENABLE_ONNX_BACKEND}")
message(STATUS "  morphizen_ENABLE_MLIR_BACKEND : ${morphizen_ENABLE_MLIR_BACKEND}")
message(STATUS "  morphizen_ENABLE_UNIT_TEST : ${morphizen_ENABLE_UNIT_TEST}")
message(STATUS "  morphizen_ENABLE_BOOST : ${morphizen_ENABLE_BOOST}")
message(STATUS "  morphizen_ENABLE_ONNX_SCHEMA_SUPPORT : ${morphizen_ENABLE_ONNX_SCHEMA_SUPPORT}")
message(STATUS "  morphizen_ENABLE_PATTERN_MATCHING : ${morphizen_ENABLE_PATTERN_MATCHING}")
message(STATUS "  morphizen_ENABLE_HIP_GPU_ALLOCATOR : ${morphizen_ENABLE_HIP_GPU_ALLOCATOR}")
