##
# ** Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
# ** Licensed under the MIT License.
##


# This file is used to set options for MorphiZen

# MorphiZen options

# enable morphizen-core-dynamic or not. when VAIP is built as a standalone library, this option should be ON
# when VAIP is built as part of onnxruntime, this option should be OFF
execute_process(
    COMMAND git rev-parse HEAD
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE GIT_VERSION_FOUND
  )
set(morphizen_CORE_DYNAMIC_UNIQUE_ID "morphizen-core-dynamic-${GIT_VERSION}" CACHE STRING "the unique name for morphizen-core-dynamic")
if (TARGET onnxruntime_providers_vitisai)
  set(morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC_DEFAULT OFF)
  set(morphizen_WITH_VAIP_CONFIG_FILE_DEFAULT OFF)
  set(morphizen_ENABLE_UNIT_TEST_DEFAULT ON)
  set(morphizen_ONNXRUNTIME_VITISAI_EP_TARGET_DEFAULT "onnxruntime_providers_vitisai")
  set(TRIM_CONFIG_DEFAULT ON)
else()
  set(morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC_DEFAULT ON)
  set(morphizen_WITH_VAIP_CONFIG_FILE_DEFAULT ON)
  set(morphizen_ENABLE_UNIT_TEST_DEFAULT ON)
  set(morphizen_ONNXRUNTIME_VITISAI_EP_TARGET_DEFAULT ${morphizen_CORE_DYNAMIC_UNIQUE_ID})
  set(TRIM_CONFIG_DEFAULT OFF)
endif()
option(morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC "enable morphizen-core-dynamic or not" ${morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC_DEFAULT})

set(morphizen_ONNXRUNTIME_VITISAI_EP_TARGET ${morphizen_ONNXRUNTIME_VITISAI_EP_TARGET_DEFAULT} CACHE STRING "the name of target whose output name is onnxruntime_vitisai_ep")
# enable morphizen unit test or not
option(morphizen_ENABLE_UNIT_TEST "enable vaip unit test or not" ${morphizen_ENABLE_UNIT_TEST_DEFAULT})
#
# to build MorphiZen, we need to download source code of onnxruntime
# and build it along with MorphiZen
#
set(ONNXRUNTIME_SOURCE_TREE_DIR "${CMAKE_SOURCE_DIR}/../onnxruntime" CACHE PATH "Path to the root of the ONNX Runtime source tree")
#
# it is possible to emebed xclbin files in the binary, assume the xclbin files are in the directory
#
set(VAIP_XCLBIN_DIR ${CMAKE_SOURCE_DIR}/../vaip_xclbin CACHE PATH "Path to the directory containing xclbin files")

# morphizen_WITH_VAIP_CONFIG_FILE = ON if build with default vaip
# config in morphizen-core-dynamic, i.e. onnxruntime_vitisai_ep.dll
# morphizen_WITH_VAIP_CONFIG_FILE = OFF if morphizen is build as part
# of onnxruntime, the default config is read from a plugin.
option(morphizen_WITH_VAIP_CONFIG_FILE "build with default vaip config in morphizen-core-dynamic, i.e. onnxruntime_vitisai_ep.dll" ${morphizen_WITH_VAIP_CONFIG_FILE_DEFAULT})
#
# it is possible to embed json files in the binary, assume the json files are in the directory
set(VAIP_JSON_CONFIG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/vaip-core/etc/vaip_config.json" CACHE FILEPATH "Path to the file containing vaip_config.json files")

# it is possible to embed version_info.txt files in the binary, assume the version_info.txt files are in the directory
# version_info.txt files are generated by the script vaip_version_info.hpp.inc.py
# `#` is used as a comment in the version_info.txt files
# each line in the version_info.txt files contains three columns separated by `;'
# the first column of the version_info.txt files is the component name
# the second column of the version_info.txt files is the git commit hash
# the third column of the version_info.txt files is the version id
# see etc/version_info.txt as an example
set(VAIP_VERSEION_INFO_FILE "${CMAKE_CURRENT_SOURCE_DIR}/vaip-core/etc/version_info.txt" CACHE FILEPATH "Path to the file containing version_info.txt files")

#
set(morphizen_OUTPUT_NAME "onnxruntime_vitisai_ep" CACHE STRING "Output name of MorphiZen library")

## this optio is used to trim vaip_config.json, we choose the original name for backward compatibility.
option(TRIM_CONFIG "trim default vaip_config.json" "${TRIM_CONFIG_DEFAULT}")
# print all options
message(STATUS "MorphiZen OPTIONS:")
message(STATUS "  morphizen_ONNXRUNTIME_VITISAI_EP_TARGET : ${morphizen_ONNXRUNTIME_VITISAI_EP_TARGET}")
message(STATUS "  morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC : ${morphizen_ENABLE_MORPHIZEN_CORE_DYNAMIC}")
message(STATUS "  VAIP_XCLBIN_DIR : ${VAIP_XCLBIN_DIR}")
message(STATUS "  ONNX_RUNTIME_SOURCE_TREE_DIR : ${ONNXRUNTIME_SOURCE_TREE_DIR}")
message(STATUS "  morphizen_WITH_VAIP_CONFIG_FILE : ${morphizen_WITH_VAIP_CONFIG_FILE}")
message(STATUS "  VAIP_JSON_CONFIG_FILE : ${VAIP_JSON_CONFIG_FILE}")
message(STATUS "  VAIP_VERSEION_INFO_FILE : ${VAIP_VERSEION_INFO_FILE}")
message(STATUS "  morphizen_OUTPUT_NAME : ${morphizen_OUTPUT_NAME}")
message(STATUS "  TRIM_CONFIG : ${TRIM_CONFIG}")
message(STATUS "  BUILD_PYTHON : ${BUILD_PYTHON}")
