#!/usr/bin/env python3
#
# Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# Licensed under the MIT License.
#
"""Extract the device half of a .hip file into a header hipRTC can compile.

Splitting by hand does not scale: matmul_nbits alone has 33 device blocks
interleaved with 71 host ones. The rule here is deliberately conservative --
drop only top-level items that are unmistakably host (STL, host HIP API, libc
file I/O), keep everything else. Keeping too much is safe: a constexpr table or
an unused struct compiles fine for device. Dropping too much fails the compile
loudly, which is the outcome we want over silent divergence.
"""

import argparse
import re
import sys

HOST_MARKERS = (
    "std::",
    "fopen",
    "fclose",
    "fprintf",
    "fgets",
    "fscanf",
    "getenv",
    "_dupenv_s",
    "hipLaunchKernelGGL",
    "hipMalloc",
    "hipFree",
    "hipMemcpy",
    "hipMemset",
    "hipStreamSynchronize",
    "hipDeviceSynchronize",
    "hipEvent",
    "hipGetDeviceProperties",
    "hipGetLastError",
    "hipFuncGetAttributes",
    "printf(",
)
DEVICE_MARKERS = ("__global__", "__device__")

RTC_PREAMBLE = """\
// GENERATED by extract_device.py -- do not edit.
//
// The device half of {src}, in the form hipRTC accepts: no <hip/*.h> (hipRTC
// injects its own preamble) and no host-only headers, but <cstdint> is required
// or int64_t resolves only inside __hip_internal.

#if !defined(__HIPCC_RTC__)
  #include <hip/hip_fp16.h>
  #include <hip/hip_runtime.h>
#endif

#include <cstdint>

#if defined(__HIPCC_RTC__)
  // hipRTC supplies the math functions but not the <math.h> macros, and <cmath>
  // conflicts with clang's HIP mode.
  #define INFINITY __builtin_inff()
  #define NAN __builtin_nanf("")
#endif
"""


def split_top_level(lines):
    """Yield (start, end, text) for each top-level item, 0-based inclusive."""
    depth = 0
    i = 0
    n = len(lines)
    while i < n:
        raw = lines[i]
        stripped = raw.strip()
        # Block comments have to be skipped explicitly, otherwise the scan
        # treats the opening /* as the start of a definition and swallows
        # everything up to the next semicolon.
        if depth == 0 and stripped.startswith("/*"):
            while i < n and "*/" not in lines[i]:
                i += 1
            i += 1
            continue
        if depth == 0 and stripped and not stripped.startswith("//"):
            start = i
            body = []
            d = 0
            seen_brace = False
            j = i
            while j < n:
                body.append(lines[j])
                # A macro continues while it ends in a backslash.
                if lines[j].lstrip().startswith("#") and not seen_brace:
                    if lines[j].rstrip().endswith("\\"):
                        j += 1
                        continue
                    break
                d += lines[j].count("{") - lines[j].count("}")
                if "{" in lines[j]:
                    seen_brace = True
                if seen_brace and d <= 0:
                    break
                if not seen_brace and lines[j].rstrip().endswith(";"):
                    break
                j += 1
            yield start, j, "".join(body)
            i = j + 1
            continue
        depth += raw.count("{") - raw.count("}")
        i += 1


def classify(text):
    head = text[:400]
    if any(m in head for m in DEVICE_MARKERS):
        return "device"
    if text.lstrip().startswith("#include"):
        return "include"
    if any(m in text for m in HOST_MARKERS):
        return "host"
    return "neutral"


DECL_NAME = re.compile(r"(\w+)\s*[\(\[=;]")


def defined_name(text):
    """Best-effort name of whatever a top-level item defines."""
    head = text.split("{", 1)[0]
    names = DECL_NAME.findall(head)
    return names[-1] if names else None


def extract(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        lines = f.readlines()

    items = [(s, e, t, classify(t)) for s, e, t in split_top_level(lines)]
    dropped = {i for i, it in enumerate(items) if it[3] in ("host", "include")}

    # Classifying each item on its own leaves callers of dropped host helpers
    # behind (hipdnn_device_is_wave64 survives while the hipGetDeviceProperties
    # probe it calls does not). Propagate until the set stops growing. Device
    # items are never dropped -- if one of them needs a host symbol that is a
    # real problem and the compile should say so.
    changed = True
    while changed:
        changed = False
        gone = {defined_name(items[i][2]) for i in dropped}
        gone.discard(None)
        for i, (_, _, text, kind) in enumerate(items):
            if i in dropped or kind == "device":
                continue
            body = text.split("{", 1)[-1]
            if any(re.search(rf"\b{re.escape(g)}\b", body) for g in gone):
                dropped.add(i)
                changed = True

    kept = [(s, e, t) for i, (s, e, t, _) in enumerate(items) if i not in dropped]
    drop = [(s, e, t) for i, (s, e, t, _) in enumerate(items) if i in dropped]
    return kept, drop


def main():
    ap = argparse.ArgumentParser()
    # Local headers the kernel file includes have to be inlined ahead of it:
    # hipRTC resolves no include paths of its own.
    ap.add_argument("sources", nargs="+")
    ap.add_argument("--output", required=True)
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    src_name = args.sources[-1].replace("\\", "/").split("/")[-1]
    out = [RTC_PREAMBLE.format(src=src_name), "\n"]
    total_kept = total_dropped = 0

    for path in args.sources:
        kept, dropped = extract(path)
        total_kept += sum(e - s + 1 for s, e, _ in kept)
        total_dropped += sum(e - s + 1 for s, e, _ in dropped)
        name = path.replace("\\", "/").split("/")[-1]
        out.append(f"\n// ---- from {name} ----\n\n")
        for _, _, text in kept:
            out.append(text)
            if not text.endswith("\n"):
                out.append("\n")
            out.append("\n")
        if args.report:
            print(f"  {name:34} kept {len(kept):3} items / dropped {len(dropped):3}")

    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(out))

    if args.report:
        print(
            f"kept {total_kept} lines, dropped {total_dropped} lines -> {args.output}"
        )


if __name__ == "__main__":
    sys.exit(main())
