##
## Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
## Licensed under the MIT License.
##
runs:
  using: "composite"
  steps:
    - name: Set env var (Linux/macOS)
      if: runner.os != 'Windows'
      run: echo "Z1AIEBUILD_GHE_PAT=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" >> $GITHUB_ENV
      shell: bash

    - name: Set env var (Windows)
      if: runner.os == 'Windows'
      run: echo "Z1AIEBUILD_GHE_PAT=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" >> $env:GITHUB_ENV
      shell: powershell
