//
// Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
// Licensed under the MIT License.
//

//===----------------------------------------------------------------------===//
// Onnx_GatherNDOp
//===----------------------------------------------------------------------===//

def Onnx_GatherNDOp : Onnx_Op<"GatherND", [Pure]> {
  let summary = "ONNX GatherND, schema version 13";

  let description = [{
    Given `data` tensor of rank `r` >= 1, `indices` tensor of rank `q` >= 1, and `batch_dims` integer `b`, this operator gathers
    slices of `data` into an output tensor of rank `q + r - indices_shape[-1] - 1 - b`.

    `indices` is an q-dimensional integer tensor, best thought of as a `(q-1)`-dimensional tensor of index-tuples into `data`,
    where each element defines a slice of `data`

    `batch_dims` (denoted as `b`) is an integer indicating the number of batch dimensions, i.e the leading `b` number of dimensions of
    `data` tensor and `indices` are representing the batches, and the gather starts from the `b+1` dimension.

    Some salient points about the inputs' rank and shape:

    1) r >= 1 and q >= 1 are to be honored. There is no dependency condition to be met between ranks `r` and `q`

    2) The first `b` dimensions of the shape of `indices` tensor and `data` tensor must be equal.

    3) b < min(q, r) is to be honored.

    4) The `indices_shape[-1]` should have a value between 1 (inclusive) and rank `r-b` (inclusive)

    5) All values in `indices` are expected to be within bounds [-s, s-1] along axis of size `s` (i.e.) `-data_shape[i] <= indices[...,i] <= data_shape[i] - 1`.
       It is an error if any of the index values are out of bounds.

    The output is computed as follows:

    The output tensor is obtained by mapping each index-tuple in the `indices` tensor to the corresponding slice of the input `data`.

    1) If `indices_shape[-1] > r-b` => error condition

    2) If `indices_shape[-1] == r-b`, since the rank of `indices` is `q`, `indices` can be thought of as `N` `(q-b-1)`-dimensional tensors
       containing 1-D tensors of dimension `r-b`, where `N` is an integer equals to the product of 1 and all the elements in the batch dimensions
       of the indices_shape. Let us think of each such `r-b` ranked tensor as `indices_slice`. Each *scalar value* corresponding to `data[0:b-1,indices_slice]`
       is filled into the corresponding location of the `(q-b-1)`-dimensional tensor to form the `output` tensor (Example 1 below)

    3) If `indices_shape[-1] < r-b`, since the rank of `indices` is `q`, `indices` can be thought of as `N` `(q-b-1)`-dimensional tensor
       containing 1-D tensors of dimension `< r-b`. Let us think of each such tensors as `indices_slice`. Each *tensor slice* corresponding
       to `data[0:b-1, indices_slice , :]` is filled into the corresponding location of the `(q-b-1)`-dimensional tensor
       to form the `output` tensor (Examples 2, 3, 4 and 5 below)

    This operator is the inverse of `ScatterND`.

    **Example 1**

    ```
    batch_dims = 0
    data    = [[0,1],[2,3]]   # data_shape    = [2, 2]
    indices = [[0,0],[1,1]]   # indices_shape = [2, 2]
    output  = [0,3]           # output_shape  = [2]
    ```

    **Example 2**

    ```
    batch_dims = 0
    data    = [[0,1],[2,3]]  # data_shape    = [2, 2]
    indices = [[1],[0]]      # indices_shape = [2, 1]
    output  = [[2,3],[0,1]]  # output_shape  = [2, 2]
    ```

    **Example 3**

    ```
    batch_dims = 0
    data    = [[[0,1],[2,3]],[[4,5],[6,7]]] # data_shape    = [2, 2, 2]
    indices = [[0,1],[1,0]]                 # indices_shape = [2, 2]
    output  = [[2,3],[4,5]]                 # output_shape  = [2, 2]
    ```

    **Example 4**

    ```
    batch_dims = 0
    data    = [[[0,1],[2,3]],[[4,5],[6,7]]] # data_shape    = [2, 2, 2]
    indices = [[[0,1]],[[1,0]]]             # indices_shape = [2, 1, 2]
    output  = [[[2,3]],[[4,5]]]             # output_shape  = [2, 1, 2]
    ```

    **Example 5**

    ```
    batch_dims = 1
    data    = [[[0,1],[2,3]],[[4,5],[6,7]]] # data_shape    = [2, 2, 2]
    indices = [[1],[0]]                     # indices_shape = [2, 1]
    output  = [[2,3],[4,5]]                 # output_shape  = [2, 2]
    ```
  }];

  let arguments = (ins
    AnyTypeOf<[
      TensorOf<[UI8]>, TensorOf<[UI16]>, TensorOf<[UI32]>, TensorOf<[UI64]>,
      TensorOf<[I8]>, TensorOf<[I16]>, TensorOf<[I32]>, TensorOf<[I64]>,
      TensorOf<[BF16]>, TensorOf<[F16]>, TensorOf<[F32]>, TensorOf<[F64]>,
      TensorOf<[I1]>, TensorOf<[Complex<F32>]>, TensorOf<[Complex<F64>]>
    ]>:$data,
    TensorOf<[I64]>:$indices,
    DefaultValuedAttr<SI64Attr, "0">:$batch_dims
  );

  let results = (outs
    AnyTypeOf<[
      TensorOf<[UI8]>, TensorOf<[UI16]>, TensorOf<[UI32]>, TensorOf<[UI64]>,
      TensorOf<[I8]>, TensorOf<[I16]>, TensorOf<[I32]>, TensorOf<[I64]>,
      TensorOf<[BF16]>, TensorOf<[F16]>, TensorOf<[F32]>, TensorOf<[F64]>,
      TensorOf<[I1]>, TensorOf<[Complex<F32>]>, TensorOf<[Complex<F64>]>
    ]>:$output
  );
}
