##
# ** Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
# ** Licensed under the MIT License.
##

load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "pattern_proto",
    srcs = ["proto/pattern.proto"],
    strip_import_prefix = "proto",
    visibility = ["//visibility:public"],
)

cc_proto_library(
    name = "pattern_cc_proto",
    deps = [":pattern_proto"],
    visibility = ["//visibility:public"],
)
