##
## Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
## Licensed under the MIT License.
##
name: build-and-test-lnx

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
  push:
    branches:
      - main

env:
  ORT_BRANCH_NAME: morphizen-ci

jobs:
  build_and_test:
    if: github.event.pull_request.draft == false
    runs-on: [morphizen_lnx]
    strategy:
      matrix:
        os: [ Linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history for all branches and tags
          show-progress: false

      - name: get Onnxruntime SHA1
        id: ort-commit
        run: |
          hash=$(git ls-remote  git@gitenterprise.xilinx.com:VitisAI/onnxruntime.git morphizen-ci | cut -f 1)
          echo "commit_hash=$hash"
          echo "commit_hash=$hash" >> $GITHUB_OUTPUT

      - name: set credential
        uses: ./.github/actions/set-env

      - name: build docker
        id: build_docker
        working-directory: ${{ github.workspace }}/.github/actions/buid-and-test-lnx
        run: |
          set -e
          ORT_COMMIT_ID=${{ steps.ort-commit.outputs.commit_hash }}
          SHORT_ORT_COMMIT_ID=${ORT_COMMIT_ID:0:7}
          echo "${{ env.Z1AIEBUILD_GHE_PAT }}" >github.token
          docker build -t morphizen-ci:v1.0-${SHORT_ORT_COMMIT_ID} \
            --progress=plain --secret id=github_token,src=github.token  \
            --build-arg ORT_COMMIT_ID=${{ steps.ort-commit.outputs.commit_hash }} \
            .

      - name: Checkout VitisAI/onnxruntime
        if: steps.cache-onnxruntime-and-deps.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ env.Z1AIEBUILD_GHE_PAT }}
          repository: VitisAI/onnxruntime
          path: onnxruntime
          ref: ${{ env.ORT_BRANCH_NAME }}
          show-progress: false

      - name: Checkout VitisAI/morphizen-demo
        uses: actions/checkout@v4
        with:
          repository: VitisAI/morphizen-demo
          path: morphizen-demo
          ref: dev
          token: ${{ env.Z1AIEBUILD_GHE_PAT }}
          show-progress: false

      - name: run docker
        id: run_docker
        working-directory: ${{ github.workspace }}/.github/actions/buid-and-test-lnx
        run: |
          set -e
          set -x
          ORT_COMMIT_ID=${{ steps.ort-commit.outputs.commit_hash }}
          SHORT_ORT_COMMIT_ID=${ORT_COMMIT_ID:0:7}
          mkdir -p .local # for pip install --user
          docker run --rm \
            -w /github/workspace \
            -v ${{ github.workspace }}:/github/workspace \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e HOST_USER_NAME=`id -un` \
            -e HOST_USER_ID=`id -u` \
            -e VAI_RT_PREFIX=/workspace/local \
            -e VAI_RT_BUILD_DIR=/workspace/build \
            -e VAI_RT_WORKSPACE=/github/workspace \
            morphizen-ci:v1.0-${SHORT_ORT_COMMIT_ID} \
            bash ./tools/build_and_test.sh
