name: build-deps

on:
    workflow_dispatch:
    # pull_request:

env:
    VAI_RT_PREFIX: ${{ github.workspace }}/gi
    VAI_RT_WORKSPACE: ${{ github.workspace }}
    VAI_RT_BUILD_DIR: ${{ github.workspace }}/gb
    MY_GITHUB_TOKEN : ${{ secrets.MY_GITHUB_TOKEN }}
    ORT_BRANCH_NAME: morphizen-ci
jobs:
  build-deps:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows_vitisai ]
    outputs:
      commit_hash: ${{ steps.ort-commit.outputs.commit_hash }}
    steps:
      # pitfall: we must update the source code to the latest commit with actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: get Onnxruntime SHA1
        id: ort-commit
        run: |
          $ErrorActionPreference = "Stop"
          $hash = git ls-remote git@gitenterprise.xilinx.com:VitisAI/onnxruntime.git "$Env:ORT_BRANCH_NAME" |
             ForEach-Object { ($_ -split "`t")[0] }
          echo "commit_hash=$hash" >> $env:GITHUB_OUTPUT

      - name: Cache installed ONNXRuntime and deps
        id: cache-onnxruntime-and-deps
        uses: actions/cache@v3
        with:
              path: ${{ env.VAI_RT_PREFIX }}
              key: ort-install-${{ steps.ort-commit.outputs.commit_hash }}-with-deps


      - name: Checkout VitisAI/onnxruntime
        if: steps.cache-onnxruntime-and-deps.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.Z1AIEBUILD_GHE_PAT }}
          repository: VitisAI/onnxruntime
          path: onnxruntime
          ref: ${{ env.ORT_BRANCH_NAME }}

      - name: Checkout VitisAI/vai-rt
        if: steps.cache-onnxruntime-and-deps.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.Z1AIEBUILD_GHE_PAT }}
            repository: VitisAI/vai-rt
            path: vai-rt
            ref: cp_dev

      - name: build and install onnxrutime and deps
        if: steps.cache-onnxruntime-and-deps.outputs.cache-hit != 'true'
        run: |
            echo "build and install onnxrutime and deps.."
            # show first 3 line of the script
            git status
            git fetch --unshallow
            git log -n 3
            git status
            Get-ChildItem -Path "${{ github.workspace}}/tools"
            echo "show first 3 line of the script"
            Get-Content "${{ github.workspace}}/tools/build_ort_and_deps.ps1" | Select-Object -First 3
            . ${{ github.workspace}}/tools/build_ort_and_deps.ps1

      - name: check workspace
        run: |
            echo "check workspace"
            Get-ChildItem -Path "${{ github.workspace}}/.github/workflows"
            git fetch --unshallow
            git log -n 3
            git status
            Get-Content "${{ github.workspace}}/.github/workflows/build_and_test.yml" | Select-Object -First 3

  display-commit-hash:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows_vitisai ]
    needs: build-deps
    steps:
      - name: Display Commit Hash
        run: |
          echo "Commit Hash: ${{ needs.build-deps.outputs.commit_hash }}"

  job-build-and-test:
    needs: build-deps
    uses: ./.github/workflows/build_and_test.yml
    with:
      ort_hash_id: ort-install-${{ needs.build-deps.outputs.commit_hash }}-with-deps
    secrets:
      Z1AIEBUILD_GHE_PAT: ${{ secrets.Z1AIEBUILD_GHE_PAT }}