name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref }}.lint
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows_vitisai ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'
      - name: Install lintrunner
        run: |
          python -m pip install --user lintrunner lintrunner-adapters>=0.8.0 --force-reinstall
          python -m pip install --user -r requirements-lintrunner.txt --force-reinstall
      - name: Add lintrunner to PATH
        run: |
            $scriptsPath = python -m site --user-base
            $env:Path += ";$scriptsPath\Scripts"
            echo "##[add-path]$scriptsPath\Scripts"
          shell: pwsh
      - name: Run lintrunner on all files
        run: |
          python -m lintrunner init
          python -m lintrunner -v --force-color --all-files --config-file .lintrunner.yml

