name: Lint

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}.lint
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows_vitisai ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install lintrunner
        run: |
          python -m pip install lintrunner lintrunner-adapters>=0.8.0 --force-reinstall
          python -m pip install -r requirements-lintrunner.txt --force-reinstall

      - name: Add user Scripts folder to PATH
        run: |
          $userBase = python -m site --user-base
          $scriptsPath = "$userBase\Scripts"
          "Adding $scriptsPath to PATH"
          "$scriptsPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run lintrunner
        run: |
          lintrunner init
          lintrunner -v --force-color --all-files

