##
## Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
## Licensed under the MIT License.
##
name: main.pull_request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
  push:
    branches:
      - main


env:
  VAI_RT_PREFIX: ${{ github.workspace }}/gi
  VAI_RT_WORKSPACE: ${{ github.workspace }}
  VAI_RT_BUILD_DIR: ${{ github.workspace }}/gb

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows_vitisai ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history for all branches and tags
          show-progress: false

      - name: Check code style
        uses: ./.github/actions/lint

  build-deps-and-build-and-test:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows_vitisai ]
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history for all branches and tags
          lfs: true
          show-progress: false
      - name: set credential
        uses: ./.github/actions/set-env

      - name: Ensure Git LFS files are pulled
        run: |
          git lfs install
          git lfs pull

      - name: build ort and deps
        uses: ./.github/actions/build-deps
        id: build-deps-action
        with:
          token: ${{ env.Z1AIEBUILD_GHE_PAT }}
          onnxruntime_branch_name: morphizen-ci

      # build-and-test job depends on build-deps job, because cache
      # cannot be shared between jobs, potentially jobs allocated to
      # different runners.
      - name: build and test
        uses: ./.github/actions/build-and-test
        with:
          ort_hash_id: ${{ steps.build-deps-action.outputs.cache_key }}
          onnxruntime_branch_name: morphizen-ci
          token: ${{ env.Z1AIEBUILD_GHE_PAT }}
