##
## Copyright (C) 2023 - 2025 Advanced Micro Devices, Inc. All rights reserved.
## Licensed under the MIT License.
##
name: sync_onnxruntime
on:
  workflow_dispatch:
  schedule:
    # Every day at midnight Beijing time (UTC+8)
    - cron: '0 16 * * *'

env:
  VAI_RT_PREFIX: ${{ github.workspace }}/gi
  VAI_RT_WORKSPACE: ${{ github.workspace }}
  VAI_RT_BUILD_DIR: ${{ github.workspace }}/gb

jobs:
  sync_onnxruntime_code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows_vitisai ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: set credential
        uses: ./.github/actions/set-env

      - name: Checkout VitisAI/onnxruntime
        uses: actions/checkout@v4
        with:
          token: ${{ env.Z1AIEBUILD_GHE_PAT }}
          repository: VitisAI/onnxruntime
          path: onnxruntime
          ref: morphizen-ci-test
          fetch-depth: 0  # Fetch morphizen-ci-test branch with all history for rebase
          show-progress: false

      - name: Sync github/onnxruntime
        run: |
          set -e
          cd onnxruntime
          # fetch upstream main branch
          git fetch https://github.com/microsoft/onnxruntime.git main
          head_commit=$(git rev-parse HEAD)
          echo "github/onnxruntime will upgrade to commit ID $(git rev-parse FETCH_HEAD)"
          # all patches in morphizen-ci-test branch are already applied to main branch,
          git rebase FETCH_HEAD
          git push origin HEAD:refs/heads/morphizen-ci-test --force
          echo "sync onnxruntime/morphizen-ci-test commit ID from $head_commit to $(git ls-remote origin refs/heads/morphizen-ci-test)"

        shell: bash

      - name: build deps
        uses: ./.github/actions/build-deps
        id: build-deps-action
        with:
          token: ${{ env.Z1AIEBUILD_GHE_PAT }}
          onnxruntime_branch_name: morphizen-ci-test

      - name: build llvm
        uses: ./.github/actions/build-llvm
        id: build-llvm-action
        with:
          token: ${{ env.Z1AIEBUILD_GHE_PAT }}
      # build-and-test job depends on build-deps job, because cache
      # cannot be shared between jobs, potentially jobs allocated to
      # different runners.
      - name: build and test
        uses: ./.github/actions/build-and-test
        with:
          ort_hash_id: ${{ steps.build-deps-action.outputs.cache_key }}
          onnxruntime_branch_name: morphizen-ci-test
          token: ${{ env.Z1AIEBUILD_GHE_PAT }}

      - name: update morphizen-ci branch
        run: |
          set -e
          cd onnxruntime
          echo "sync onnxruntime commit ID from $(git ls-remote origin refs/heads/morphizen-ci) to $(git rev-parse FETCH_HEAD)"
          git push origin HEAD:refs/heads/morphizen-ci --force
          git ls-remote origin morphizen-ci
        shell: bash
