name: Submit PR to update cmake/deps.txt in vaip

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
    VAIP_BRANCH: cp_dev
    VAIP_REPO: git@gitenterprise.xilinx.com:VitisAI/vaip.git

jobs:
  update-deps-txt-in-vaip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows_vitisai ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history for all branches and tags
          show-progress: false


      - name: Submit PR to update cmake/deps.txt in vaip
        shell: powershell
        run: |
            echo "Submit PR to update cmake/deps.txt in vaip"
            . ${{ github.workspace}}/tools/submit_vaip_pr.ps1
        env:
            MY_GHE_TOKEN : ${{ secrets.Z1AIEBUILD_GHE_PAT }}
            VAIP_REMOTE_BRANCH: ${{ env.VAIP_BRANCH }}